create table aeroporti (
	cod_aeroporto INT AUTO_INCREMENT,
	nome VARCHAR(50),
	citta VARCHAR(50),
	paese VARCHAR(50),
    PRIMARY KEY(cod_aeroporto)
);
insert into aeroporti (nome, citta, paese) values ('Shanshan Airport', 'Shanshan', 'CN');
insert into aeroporti (nome, citta, paese) values ('Valle Del Conlara International Airport', 'Merlo', 'AR');
insert into aeroporti (nome, citta, paese) values ('João Durval Carneiro Airport', 'Feira De Santana', 'BR');
insert into aeroporti (nome, citta, paese) values ('Hluhluwe Airport', 'Hluhluwe', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Fort Mackay / Horizon Airport', 'Fort Mackay', 'CA');
insert into aeroporti (nome, citta, paese) values ('Girona Airport', 'Girona', 'ES');
insert into aeroporti (nome, citta, paese) values ('Qacha''s Nek Airport', 'Qacha''s Nek', 'LS');
insert into aeroporti (nome, citta, paese) values ('Pincher Creek Airport', 'Pincher Creek', 'CA');
insert into aeroporti (nome, citta, paese) values ('Los Roques Airport', 'Gran Roque Island', 'VE');
insert into aeroporti (nome, citta, paese) values ('Gush Katif Airport', 'Khan Yunis', 'PS');
insert into aeroporti (nome, citta, paese) values ('Eastern WV Regional Airport/Shepherd Field', 'Martinsburg', 'US');
insert into aeroporti (nome, citta, paese) values ('Eagle Air Park', 'Brazoria', 'US');
insert into aeroporti (nome, citta, paese) values ('Mário Pereira Lopes–São Carlos Airport', 'São Carlos', 'BR');
insert into aeroporti (nome, citta, paese) values ('Southampton Airport', 'Southampton', 'GB');
insert into aeroporti (nome, citta, paese) values ('Diamantina Airport', 'Diamantina', 'BR');
insert into aeroporti (nome, citta, paese) values ('Umba Airport', 'Umba', 'PG');
insert into aeroporti (nome, citta, paese) values ('Kamloops Airport', 'Kamloops', 'CA');
insert into aeroporti (nome, citta, paese) values ('Adampur Airport', 'Adampur', 'IN');
insert into aeroporti (nome, citta, paese) values ('Apalapsili Airport', 'Apalapsili', 'ID');
insert into aeroporti (nome, citta, paese) values ('Douglas-Charles Airport', 'Marigot', 'DM');
insert into aeroporti (nome, citta, paese) values ('Karonga Airport', 'Karonga', 'MW');
insert into aeroporti (nome, citta, paese) values ('Mitzic Airport', 'Mitzic', 'GA');
insert into aeroporti (nome, citta, paese) values ('Hamburg Airport', 'Hamburg', 'DE');
insert into aeroporti (nome, citta, paese) values ('St George Municipal Airport', 'St George', 'US');
insert into aeroporti (nome, citta, paese) values ('Djambala Airport', 'Djambala', 'CG');
insert into aeroporti (nome, citta, paese) values ('Barakoma Airport', 'Barakoma', 'SB');
insert into aeroporti (nome, citta, paese) values ('San Angelo Regional Mathis Field', 'San Angelo', 'US');
insert into aeroporti (nome, citta, paese) values ('Bajhang Airport', 'Bajhang', 'NP');
insert into aeroporti (nome, citta, paese) values ('Chengde Puning Airport', 'Chengde', 'CN');
insert into aeroporti (nome, citta, paese) values ('Palm Beach County Glades Airport', 'Pahokee', 'US');
insert into aeroporti (nome, citta, paese) values ('King Shaka International Airport', 'Durban', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Drietabbetje Airport', 'Drietabbetje', 'SR');
insert into aeroporti (nome, citta, paese) values ('Shahroud Airport', null, 'IR');
insert into aeroporti (nome, citta, paese) values ('Myitkyina Airport', 'Myitkyina', 'MM');
insert into aeroporti (nome, citta, paese) values ('Luang Phabang International Airport', 'Luang Phabang', 'LA');
insert into aeroporti (nome, citta, paese) values ('Stauning Airport', 'Skjern / Ringkøbing', 'DK');
insert into aeroporti (nome, citta, paese) values ('Orapa Airport', 'Orapa', 'BW');
insert into aeroporti (nome, citta, paese) values ('Sept-Îles Airport', 'Sept-Îles', 'CA');
insert into aeroporti (nome, citta, paese) values ('Beaver Creek Airport', 'Beaver Creek', 'CA');
insert into aeroporti (nome, citta, paese) values ('El Bayadh Airport', 'El Bayadh', 'DZ');
insert into aeroporti (nome, citta, paese) values ('Caen-Carpiquet Airport', 'Caen/Carpiquet', 'FR');
insert into aeroporti (nome, citta, paese) values ('Candle 2 Airport', 'Candle', 'US');
insert into aeroporti (nome, citta, paese) values ('RAF Lyneham', 'Lyneham', 'GB');
insert into aeroporti (nome, citta, paese) values ('Semnan Municipal Airport', 'Semnan', 'IR');
insert into aeroporti (nome, citta, paese) values ('Chalkyitsik Airport', 'Chalkyitsik', 'US');
insert into aeroporti (nome, citta, paese) values ('Barrow County Airport', 'Winder', 'US');
insert into aeroporti (nome, citta, paese) values ('Pointe Vele Airport', 'Futuna Island', 'WF');
insert into aeroporti (nome, citta, paese) values ('Christchurch International Airport', 'Christchurch', 'NZ');
insert into aeroporti (nome, citta, paese) values ('9 de Maio - Teixeira de Freitas Airport', 'Teixeira De Freitas', 'BR');
insert into aeroporti (nome, citta, paese) values ('Jingdezhen Airport', 'Jingdezhen', 'CN');
insert into aeroporti (nome, citta, paese) values ('Osvaldo Vieira International Airport', 'Bissau', 'GW');
insert into aeroporti (nome, citta, paese) values ('Amanab Airport', 'Amanab', 'PG');
insert into aeroporti (nome, citta, paese) values ('Piatã Airport', 'Piatã', 'BR');
insert into aeroporti (nome, citta, paese) values ('Nowata Airport', null, 'PG');
insert into aeroporti (nome, citta, paese) values ('San Blas Airport', 'Wannukandi', 'PA');
insert into aeroporti (nome, citta, paese) values ('Al Dhafra Air Base', null, 'AE');
insert into aeroporti (nome, citta, paese) values ('Urad Middle Banner', 'Urad Middle Banner', 'CN');
insert into aeroporti (nome, citta, paese) values ('Fairbanks International Airport', 'Fairbanks', 'US');
insert into aeroporti (nome, citta, paese) values ('Ashley Municipal Airport', 'Ashley', 'US');
insert into aeroporti (nome, citta, paese) values ('Molokai Airport', 'Kaunakakai', 'US');
insert into aeroporti (nome, citta, paese) values ('Arua Airport', 'Arua', 'UG');
insert into aeroporti (nome, citta, paese) values ('Alxa Right Banner Badanjilin Airport', 'Badanjilin', 'CN');
insert into aeroporti (nome, citta, paese) values ('Ingham Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Achmad Yani Airport', 'Semarang-Java Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Khashm El Girba Airport', 'Khashm El Girba', 'SD');
insert into aeroporti (nome, citta, paese) values ('Utti Air Base', 'Utti / Valkeala', 'FI');
insert into aeroporti (nome, citta, paese) values ('Narrabri Airport', 'Narrabri', 'AU');
insert into aeroporti (nome, citta, paese) values ('Eagle County Regional Airport', 'Eagle', 'US');
insert into aeroporti (nome, citta, paese) values ('Sultan Khairun Babullah Airport', 'Sango-Ternate Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Óbidos Airport', 'Óbidos', 'BR');
insert into aeroporti (nome, citta, paese) values ('Sangir Airport', 'Sangir-Simbawa Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Miyazaki Airport', 'Miyazaki', 'JP');
insert into aeroporti (nome, citta, paese) values ('General Mariano Matamoros Airport', null, 'MX');
insert into aeroporti (nome, citta, paese) values ('General WM J Fox Airfield', 'Lancaster', 'US');
insert into aeroporti (nome, citta, paese) values ('York Airport', 'York', 'US');
insert into aeroporti (nome, citta, paese) values ('Winnipeg / James Armstrong Richardson International Airport', 'Winnipeg', 'CA');
insert into aeroporti (nome, citta, paese) values ('Oro Negro Airport', 'Cabimas', 'VE');
insert into aeroporti (nome, citta, paese) values ('Hastings Airport', 'Freetown', 'SL');
insert into aeroporti (nome, citta, paese) values ('Punta Colorada Airport', 'La Ribera', 'MX');
insert into aeroporti (nome, citta, paese) values ('Aribinda Airport', 'Aribinda', 'BF');
insert into aeroporti (nome, citta, paese) values ('Dracena Airport', 'Dracena', 'BR');
insert into aeroporti (nome, citta, paese) values ('Alberto Delgado Airport', 'Trinidad', 'CU');
insert into aeroporti (nome, citta, paese) values ('Bilaspur Airport', 'Bilaspur', 'IN');
insert into aeroporti (nome, citta, paese) values ('Dourados Airport', 'Dourados', 'BR');
insert into aeroporti (nome, citta, paese) values ('Vigo Airport', 'Vigo', 'ES');
insert into aeroporti (nome, citta, paese) values ('Diori Hamani International Airport', 'Niamey', 'NE');
insert into aeroporti (nome, citta, paese) values ('Houghton County Memorial Airport', 'Hancock', 'US');
insert into aeroporti (nome, citta, paese) values ('Megève Airport', 'Verdun', 'FR');
insert into aeroporti (nome, citta, paese) values ('Santa Cruz Sky Park', 'Scotts Valley', 'US');
insert into aeroporti (nome, citta, paese) values ('Wolter Monginsidi Airport', 'Kendari-Celebes Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('McArthur River Mine Airport', 'McArthur River Mine', 'AU');
insert into aeroporti (nome, citta, paese) values ('Adıyaman Airport', 'Adıyaman', 'TR');
insert into aeroporti (nome, citta, paese) values ('Westerly State Airport', 'Westerly', 'US');
insert into aeroporti (nome, citta, paese) values ('Cape Gloucester Airport', 'Cape Gloucester', 'PG');
insert into aeroporti (nome, citta, paese) values ('Rosario Seaplane Base', 'Rosario', 'US');
insert into aeroporti (nome, citta, paese) values ('Yakima Air Terminal McAllister Field', 'Yakima', 'US');
insert into aeroporti (nome, citta, paese) values ('Fada N''gourma Airport', 'Fada N''gourma', 'BF');
insert into aeroporti (nome, citta, paese) values ('Nain Airport', 'Nain', 'CA');
insert into aeroporti (nome, citta, paese) values ('Gunnison Crested Butte Regional Airport', 'Gunnison', 'US');
insert into aeroporti (nome, citta, paese) values ('Rar Gwamar Airport', 'Dobo-Warmar Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Gwaunaru''u Airport', 'Auki', 'SB');
insert into aeroporti (nome, citta, paese) values ('Hopetoun Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Rockwood Municipal Airport', 'Rockwood', 'US');
insert into aeroporti (nome, citta, paese) values ('Edmonton International Airport', 'Edmonton', 'CA');
insert into aeroporti (nome, citta, paese) values ('RAF Honington', 'Thetford', 'GB');
insert into aeroporti (nome, citta, paese) values ('Buochs Airport', 'Buochs', 'CH');
insert into aeroporti (nome, citta, paese) values ('Flagstaff Pulliam Airport', 'Flagstaff', 'US');
insert into aeroporti (nome, citta, paese) values ('Tokua Airport', 'Tokua', 'PG');
insert into aeroporti (nome, citta, paese) values ('Shennongjia Hongping Airport', 'Shennongjia', 'CN');
insert into aeroporti (nome, citta, paese) values ('Rand Airport', 'Johannesburg', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Welshpool Airport', 'Welshpool', 'AU');
insert into aeroporti (nome, citta, paese) values ('Tatalina LRRS Airport', 'Takotna', 'US');
insert into aeroporti (nome, citta, paese) values ('Çıldır Airport', 'Aydın', 'TR');
insert into aeroporti (nome, citta, paese) values ('Dillingham Airport', 'Dillingham', 'US');
insert into aeroporti (nome, citta, paese) values ('Kazan International Airport', 'Kazan', 'RU');
insert into aeroporti (nome, citta, paese) values ('Danbury Municipal Airport', 'Danbury', 'US');
insert into aeroporti (nome, citta, paese) values ('McMinn County Airport', 'Athens', 'US');
insert into aeroporti (nome, citta, paese) values ('Soroako Airport', 'Soroako-Celebes Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Hola Airport', 'Hola', 'KE');
insert into aeroporti (nome, citta, paese) values ('Koyukuk Airport', 'Koyukuk', 'US');
insert into aeroporti (nome, citta, paese) values ('Sri Guru Ram Dass Jee International Airport', 'Amritsar', 'IN');
insert into aeroporti (nome, citta, paese) values ('Fort Worth Alliance Airport', 'Fort Worth', 'US');
insert into aeroporti (nome, citta, paese) values ('Industrial Airpark', 'Hobbs', 'US');
insert into aeroporti (nome, citta, paese) values ('Dunsmuir Muni-Mott Airport', 'Dunsmuir', 'US');
insert into aeroporti (nome, citta, paese) values ('Mulege Airport', 'Mulege', 'MX');
insert into aeroporti (nome, citta, paese) values ('Groote Eylandt Airport', 'Groote Eylandt', 'AU');
insert into aeroporti (nome, citta, paese) values ('Paris-Le Bourget Airport', 'Paris', 'FR');
insert into aeroporti (nome, citta, paese) values ('Shaikh Zaid Airport', 'Rahim Yar Khan', 'PK');
insert into aeroporti (nome, citta, paese) values ('Centralia Municipal Airport', 'Centralia', 'US');
insert into aeroporti (nome, citta, paese) values ('Governor''s Harbour Airport', 'Governor''s Harbour', 'BS');
insert into aeroporti (nome, citta, paese) values ('North Texas Regional Airport/Perrin Field', 'Sherman/Denison', 'US');
insert into aeroporti (nome, citta, paese) values ('Gustavo Vargas Airport', 'Tame', 'CO');
insert into aeroporti (nome, citta, paese) values ('Sumburgh Airport', 'Lerwick', 'GB');
insert into aeroporti (nome, citta, paese) values ('Southport Airport', 'Portage la Prairie', 'CA');
insert into aeroporti (nome, citta, paese) values ('Horsham Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Achmad Yani Airport', 'Semarang-Java Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Punta Chivato Airport', 'Punta Chivato', 'MX');
insert into aeroporti (nome, citta, paese) values ('Dorobisoro Airport', 'Dorobisoro', 'PG');
insert into aeroporti (nome, citta, paese) values ('Aden International Airport', 'Aden', 'YE');
insert into aeroporti (nome, citta, paese) values ('Greenville Airport', 'Greenville', 'US');
insert into aeroporti (nome, citta, paese) values ('Yuncheng Guangong Airport', 'Yuncheng', 'CN');
insert into aeroporti (nome, citta, paese) values ('Taichung Airport', 'Taichung City', 'TW');
insert into aeroporti (nome, citta, paese) values ('Principe Airport', null, 'ST');
insert into aeroporti (nome, citta, paese) values ('Ha''il Airport', 'Ha''il', 'SA');
insert into aeroporti (nome, citta, paese) values ('Jaime Gonzalez Airport', 'Cienfuegos', 'CU');
insert into aeroporti (nome, citta, paese) values ('Amsterdam Airport Schiphol', 'Amsterdam', 'NL');
insert into aeroporti (nome, citta, paese) values ('Codrington Airport', 'Codrington', 'AG');
insert into aeroporti (nome, citta, paese) values ('Tashkent International Airport', 'Tashkent', 'UZ');
insert into aeroporti (nome, citta, paese) values ('Wiley Post Airport', 'Oklahoma City', 'US');
insert into aeroporti (nome, citta, paese) values ('Hato International Airport', 'Willemstad', 'CW');
insert into aeroporti (nome, citta, paese) values ('Schefferville Airport', 'Schefferville', 'CA');
insert into aeroporti (nome, citta, paese) values ('Jipijapa Airport', 'Jipijapa', 'EC');
insert into aeroporti (nome, citta, paese) values ('Lusikisiki Airport', 'Lusikisiki', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Ostend-Bruges International Airport', 'Ostend', 'BE');
insert into aeroporti (nome, citta, paese) values ('Merluna Airport', 'Merluna', 'AU');
insert into aeroporti (nome, citta, paese) values ('Tamchakett Airport', 'Tamchakett', 'MR');
insert into aeroporti (nome, citta, paese) values ('Goloson International Airport', 'La Ceiba', 'HN');
insert into aeroporti (nome, citta, paese) values ('Kanainj Airport', 'Kanainj', 'PG');
insert into aeroporti (nome, citta, paese) values ('Mianwali Air Base', 'Mianwali', 'PK');
insert into aeroporti (nome, citta, paese) values ('Dewitt Field,Old Town Municipal Airport', 'Old Town', 'US');
insert into aeroporti (nome, citta, paese) values ('Herrera Airport', 'Santo Domingo', 'DO');
insert into aeroporti (nome, citta, paese) values ('Tarapaina Airport', 'Tarapaina', 'SB');
insert into aeroporti (nome, citta, paese) values ('Jeki Airport', 'Lower Zambezi Natational Park', 'ZM');
insert into aeroporti (nome, citta, paese) values ('Springbok Airport', 'Springbok', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Kabala Airport', 'Kabala', 'SL');
insert into aeroporti (nome, citta, paese) values ('Gafsa Ksar International Airport', 'Gafsa', 'TN');
insert into aeroporti (nome, citta, paese) values ('Grand Rapids Itasca Co-Gordon Newstrom field', 'Grand Rapids', 'US');
insert into aeroporti (nome, citta, paese) values ('Bilaspur Airport', 'Bilaspur', 'IN');
insert into aeroporti (nome, citta, paese) values ('Flagstaff Pulliam Airport', 'Flagstaff', 'US');
insert into aeroporti (nome, citta, paese) values ('Yas Island Seaplane Base', 'Abu Dhabi', 'AE');
insert into aeroporti (nome, citta, paese) values ('Guiria Airport', null, 'VE');
insert into aeroporti (nome, citta, paese) values ('El Reno Regional Airport', 'El Reno', 'US');
insert into aeroporti (nome, citta, paese) values ('Butterworth Airport', 'Butterworth', 'MY');
insert into aeroporti (nome, citta, paese) values ('Cape Rodney Airport', 'Cape Rodney', 'PG');
insert into aeroporti (nome, citta, paese) values ('Tau Airport', 'Tau Village', 'AS');
insert into aeroporti (nome, citta, paese) values ('Beni Airport', 'Beni', 'CD');
insert into aeroporti (nome, citta, paese) values ('Lalmonirhat Airport', 'Lalmonirhat', 'BD');
insert into aeroporti (nome, citta, paese) values ('Dnipropetrovsk International Airport', 'Dnipropetrovsk', 'UA');
insert into aeroporti (nome, citta, paese) values ('Ixtapa Zihuatanejo International Airport', 'Ixtapa', 'MX');
insert into aeroporti (nome, citta, paese) values ('Mary River Aerodrome', null, 'CA');
insert into aeroporti (nome, citta, paese) values ('Sir Grantley Adams International Airport', 'Bridgetown', 'BB');
insert into aeroporti (nome, citta, paese) values ('Chevery Airport', 'Chevery', 'CA');
insert into aeroporti (nome, citta, paese) values ('Forest City Municipal Airport', 'Forest City', 'US');
insert into aeroporti (nome, citta, paese) values ('Reykhólar Airport', 'Reykhólar', 'IS');
insert into aeroporti (nome, citta, paese) values ('Corvo Airport', 'Corvo', 'PT');
insert into aeroporti (nome, citta, paese) values ('Borroloola Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Clayton Municipal Airpark', 'Clayton', 'US');
insert into aeroporti (nome, citta, paese) values ('Base de Aviação de Taubaté Airport', 'Taubaté', 'BR');
insert into aeroporti (nome, citta, paese) values ('Lafayette Regional Airport', 'Lafayette', 'US');
insert into aeroporti (nome, citta, paese) values ('Missoula International Airport', 'Missoula', 'US');
insert into aeroporti (nome, citta, paese) values ('Biggs Army Air Field (Fort Bliss)', 'Fort Bliss/El Paso', 'US');
insert into aeroporti (nome, citta, paese) values ('Shikarpur Airport', 'Shikarpur', 'PK');
insert into aeroporti (nome, citta, paese) values ('Dubuque Regional Airport', 'Dubuque', 'US');
insert into aeroporti (nome, citta, paese) values ('Radom Airport', 'Radom', 'PL');
insert into aeroporti (nome, citta, paese) values ('Lawson Army Air Field (Fort Benning)', 'Fort Benning(Columbus)', 'US');
insert into aeroporti (nome, citta, paese) values ('Detroit Lakes Airport - Wething Field', 'Detroit Lakes', 'US');
insert into aeroporti (nome, citta, paese) values ('Tekin Airport', 'Tekin', 'PG');
insert into aeroporti (nome, citta, paese) values ('Tancredo Neves International Airport', 'Belo Horizonte', 'BR');
insert into aeroporti (nome, citta, paese) values ('Midland Airpark', 'Midland', 'US');
insert into aeroporti (nome, citta, paese) values ('Port Alfred Airport', 'Port Alfred', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Saint Louis Airport', 'Saint Louis', 'SN');
insert into aeroporti (nome, citta, paese) values ('Tucupita Airport', 'Tucupita', 'VE');
insert into aeroporti (nome, citta, paese) values ('Black Tickle Airport', 'Black Tickle', 'CA');
insert into aeroporti (nome, citta, paese) values ('Cherrabun Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Nipa Airport', 'Nipa', 'PG');
insert into aeroporti (nome, citta, paese) values ('Mikkeli Airport', 'Mikkeli', 'FI');
insert into aeroporti (nome, citta, paese) values ('Guernsey Airport', 'Saint Peter Port', 'GG');
insert into aeroporti (nome, citta, paese) values ('Coromandel Aerodrome', null, 'NZ');
insert into aeroporti (nome, citta, paese) values ('Emmen Air Base', null, 'CH');
insert into aeroporti (nome, citta, paese) values ('Betioky Airport', 'Betioky', 'MG');
insert into aeroporti (nome, citta, paese) values ('Khovd Airport', 'Khovd', 'MN');
insert into aeroporti (nome, citta, paese) values ('Woja Airport', 'Woja', 'MH');
insert into aeroporti (nome, citta, paese) values ('Perth Jandakot Airport', 'Perth', 'AU');
insert into aeroporti (nome, citta, paese) values ('Pattaya Airpark', 'Pattaya', 'TH');
insert into aeroporti (nome, citta, paese) values ('Parakou Airport', 'Parakou', 'BJ');
insert into aeroporti (nome, citta, paese) values ('Bensbach Airport', 'Bensbach', 'PG');
insert into aeroporti (nome, citta, paese) values ('St Louis Regional Airport', 'Alton/St Louis', 'US');
insert into aeroporti (nome, citta, paese) values ('Paulo Afonso Airport', 'Paulo Afonso', 'BR');
insert into aeroporti (nome, citta, paese) values ('Manga Airport', 'Manga Mission', 'PG');
insert into aeroporti (nome, citta, paese) values ('Hilo International Airport', 'Hilo', 'US');
insert into aeroporti (nome, citta, paese) values ('Volta Redonda Airport', 'Volta Redonda', 'BR');
insert into aeroporti (nome, citta, paese) values ('Cangyuan Washan Airport', 'Cangyuan Va Autonomous County', 'CN');
insert into aeroporti (nome, citta, paese) values ('Kingston Norman Rogers Airport', 'Kingston', 'CA');
insert into aeroporti (nome, citta, paese) values ('Sparta Fort Mc Coy Airport', 'Sparta', 'US');
insert into aeroporti (nome, citta, paese) values ('Aribinda Airport', 'Aribinda', 'BF');
insert into aeroporti (nome, citta, paese) values ('Niort-Souché Airport', 'Niort/Souché', 'FR');
insert into aeroporti (nome, citta, paese) values ('Pickens County Airport', 'Pickens', 'US');
insert into aeroporti (nome, citta, paese) values ('Xingning Airport', 'Xingning', 'CN');
insert into aeroporti (nome, citta, paese) values ('Viru Viru International Airport', 'Santa Cruz', 'BO');
insert into aeroporti (nome, citta, paese) values ('Arvidsjaur Airport', 'Arvidsjaur', 'SE');
insert into aeroporti (nome, citta, paese) values ('Wollongong Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Machado Airport', 'Machado', 'BR');
insert into aeroporti (nome, citta, paese) values ('Chistochina Airport', 'Chistochina', 'US');
insert into aeroporti (nome, citta, paese) values ('Lastourville Airport', 'Lastourville', 'GA');
insert into aeroporti (nome, citta, paese) values ('Base Aérea de Santos Airport', 'Guarujá', 'BR');
insert into aeroporti (nome, citta, paese) values ('Gurney Airport', 'Gurney', 'PG');
insert into aeroporti (nome, citta, paese) values ('Timber Creek Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Betioky Airport', 'Betioky', 'MG');
insert into aeroporti (nome, citta, paese) values ('Minot Air Force Base', 'Minot', 'US');
insert into aeroporti (nome, citta, paese) values ('Farewell Airport', 'Farewell', 'US');
insert into aeroporti (nome, citta, paese) values ('Ardmore Downtown Executive Airport', 'Ardmore', 'US');
insert into aeroporti (nome, citta, paese) values ('Nordholz Naval Airbase', 'Cuxhaven', 'DE');
insert into aeroporti (nome, citta, paese) values ('Avon Park Executive Airport', 'Avon Park', 'US');
insert into aeroporti (nome, citta, paese) values ('Boundary Bay Airport', 'Vancouver', 'CA');
insert into aeroporti (nome, citta, paese) values ('Sde Dov Airport', 'Tel Aviv', 'IL');
insert into aeroporti (nome, citta, paese) values ('Opapimiskan Lake Airport', 'Opapimiskan Lake', 'CA');
insert into aeroporti (nome, citta, paese) values ('Pamol Airport', 'Pamol', 'MY');
insert into aeroporti (nome, citta, paese) values ('Heritage Field', 'Pottstown', 'US');
insert into aeroporti (nome, citta, paese) values ('Nanaimo Harbour Water Airport', 'Nanaimo', 'CA');
insert into aeroporti (nome, citta, paese) values ('Sheridan County Airport', 'Sheridan', 'US');
insert into aeroporti (nome, citta, paese) values ('Essen Mulheim Airport', null, 'DE');
insert into aeroporti (nome, citta, paese) values ('Pinheiro Airport', 'Pinheiro', 'BR');
insert into aeroporti (nome, citta, paese) values ('Marble Bar Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Roebourne Airport', 'Roebourne', 'AU');
insert into aeroporti (nome, citta, paese) values ('Shenzhen Bao''an International Airport', 'Shenzhen', 'CN');
insert into aeroporti (nome, citta, paese) values ('Maiana Airport', 'Maiana', 'KI');
insert into aeroporti (nome, citta, paese) values ('Bongor Airport', 'Bongor', 'TD');
insert into aeroporti (nome, citta, paese) values ('Miyako Airport', 'Miyako City', 'JP');
insert into aeroporti (nome, citta, paese) values ('Sangir Airport', 'Sangir-Simbawa Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Fleetlands Heliport', 'Gosport', 'GB');
insert into aeroporti (nome, citta, paese) values ('Venice Marco Polo Airport', 'Venice', 'IT');
insert into aeroporti (nome, citta, paese) values ('José Leonardo Chirinos Airport', 'Coro', 'VE');
insert into aeroporti (nome, citta, paese) values ('Bronson Creek Airport', 'Bronson Creek', 'CA');
insert into aeroporti (nome, citta, paese) values ('St Johns Industrial Air Park', 'St Johns', 'US');
insert into aeroporti (nome, citta, paese) values ('Swan Hill Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Anadolu Airport', 'Eskişehir', 'TR');
insert into aeroporti (nome, citta, paese) values ('Mkambati Airport', 'Mkambati', 'ZA');
insert into aeroporti (nome, citta, paese) values ('River Cess Airport/Heliport', 'River Cess', 'LR');
insert into aeroporti (nome, citta, paese) values ('Abingdon Downs Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Sesriem Airstrip', null, 'NA');
insert into aeroporti (nome, citta, paese) values ('Halliburton Field', 'Duncan', 'US');
insert into aeroporti (nome, citta, paese) values ('Melbourne International Airport', 'Melbourne', 'AU');
insert into aeroporti (nome, citta, paese) values ('Santiago Vila Airport', 'Girardot', 'CO');
insert into aeroporti (nome, citta, paese) values ('Sarakhs Airport', 'Sarakhs', 'IR');
insert into aeroporti (nome, citta, paese) values ('Prince Mohammad Bin Abdulaziz Airport', 'Medina', 'SA');
insert into aeroporti (nome, citta, paese) values ('Olympia Regional Airport', 'Olympia', 'US');
insert into aeroporti (nome, citta, paese) values ('Kugluktuk Airport', 'Kugluktuk', 'CA');
insert into aeroporti (nome, citta, paese) values ('George Downer Airport', 'Aliceville', 'US');
insert into aeroporti (nome, citta, paese) values ('Wiseman Airport', 'Wiseman', 'US');
insert into aeroporti (nome, citta, paese) values ('Locarno Airport', 'Locarno', 'CH');
insert into aeroporti (nome, citta, paese) values ('Dahl Creek Airport', 'Dahl Creek', 'US');
insert into aeroporti (nome, citta, paese) values ('Nepalgunj Airport', 'Nepalgunj', 'NP');
insert into aeroporti (nome, citta, paese) values ('Esperadinha Airport', 'Brava Island', 'CV');
insert into aeroporti (nome, citta, paese) values ('Guaporé Airport', 'Guaporé', 'BR');
insert into aeroporti (nome, citta, paese) values ('Novo Horizonte Airport', 'Novo Horizonte', 'BR');
insert into aeroporti (nome, citta, paese) values ('Coffeyville Municipal Airport', 'Coffeyville', 'US');
insert into aeroporti (nome, citta, paese) values ('Liupanshui Yuezhao Airport', 'Liupanshui', 'CN');
insert into aeroporti (nome, citta, paese) values ('Lubbock Preston Smith International Airport', 'Lubbock', 'US');
insert into aeroporti (nome, citta, paese) values ('H H Coffield Regional Airport', 'Rockdale', 'US');
insert into aeroporti (nome, citta, paese) values ('Alderney Airport', 'Saint Anne', 'GG');
insert into aeroporti (nome, citta, paese) values ('Elmendorf Air Force Base', 'Anchorage', 'US');
insert into aeroporti (nome, citta, paese) values ('Witu Airport', 'Garove Island', 'PG');
insert into aeroporti (nome, citta, paese) values ('Wang-an Airport', 'Wang-an', 'TW');
insert into aeroporti (nome, citta, paese) values ('Fort Mcpherson Airport', 'Fort Mcpherson', 'CA');
insert into aeroporti (nome, citta, paese) values ('Bewani Airport', 'Bewani', 'PG');
insert into aeroporti (nome, citta, paese) values ('San Javier Airport', 'San Javier', 'BO');
insert into aeroporti (nome, citta, paese) values ('Kudat Airport', 'Kudat', 'MY');
insert into aeroporti (nome, citta, paese) values ('Northern Maine Regional Airport at Presque Isle', 'Presque Isle', 'US');
insert into aeroporti (nome, citta, paese) values ('Tiksi Airport', 'Tiksi', 'RU');
insert into aeroporti (nome, citta, paese) values ('Forster (Wallis Is) Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Pskov Airport', 'Pskov', 'RU');
insert into aeroporti (nome, citta, paese) values ('Saurimo Airport', 'Saurimo', 'AO');
insert into aeroporti (nome, citta, paese) values ('Kigoma Airport', 'Kigoma', 'TZ');
insert into aeroporti (nome, citta, paese) values ('Aniwa Airport', 'Aniwa', 'VU');
insert into aeroporti (nome, citta, paese) values ('Sukkur Airport', 'Mirpur Khas', 'PK');
insert into aeroporti (nome, citta, paese) values ('Crossville Memorial Whitson Field', 'Crossville', 'US');
insert into aeroporti (nome, citta, paese) values ('Kulgera Airport', 'Kulgera', 'AU');
insert into aeroporti (nome, citta, paese) values ('Dakhla Airport', 'Dakhla', 'EH');
insert into aeroporti (nome, citta, paese) values ('Mayo Airport', 'Mayo', 'CA');
insert into aeroporti (nome, citta, paese) values ('Elim Airport', 'Elim', 'US');
insert into aeroporti (nome, citta, paese) values ('Whatì Airport', 'Whatì', 'CA');
insert into aeroporti (nome, citta, paese) values ('Mustique Airport', 'Mustique Island', 'VC');
insert into aeroporti (nome, citta, paese) values ('Fazenda Cataco Airport', 'Ubarana', 'BR');
insert into aeroporti (nome, citta, paese) values ('Adampur Airport', 'Adampur', 'IN');
insert into aeroporti (nome, citta, paese) values ('Nottingham Airport', 'Nottingham', 'GB');
insert into aeroporti (nome, citta, paese) values ('Pinehouse Lake Airport', 'Pinehouse Lake', 'CA');
insert into aeroporti (nome, citta, paese) values ('Rughenda Airfield', 'Butembo', 'CD');
insert into aeroporti (nome, citta, paese) values ('Nan Airport', null, 'TH');
insert into aeroporti (nome, citta, paese) values ('Meghauli Airport', 'Meghauli', 'NP');
insert into aeroporti (nome, citta, paese) values ('Kherson International Airport', 'Kherson', 'UA');
insert into aeroporti (nome, citta, paese) values ('Marla Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Kelsey Airport', 'Kelsey', 'CA');
insert into aeroporti (nome, citta, paese) values ('Seymour Airport', 'Baltra', 'EC');
insert into aeroporti (nome, citta, paese) values ('Rio Grande Airport', 'Rio Grande', 'BR');
insert into aeroporti (nome, citta, paese) values ('Kasese Airport', 'Kasese', 'UG');
insert into aeroporti (nome, citta, paese) values ('Clermont-Ferrand Auvergne Airport', 'Clermont-Ferrand/Auvergne', 'FR');
insert into aeroporti (nome, citta, paese) values ('San Fernando Airport', 'Los Angeles', 'US');
insert into aeroporti (nome, citta, paese) values ('Melbourne Moorabbin Airport', 'Melbourne', 'AU');
insert into aeroporti (nome, citta, paese) values ('Mount Gordon Airport', 'Mount Gordon Mine', 'AU');
insert into aeroporti (nome, citta, paese) values ('Metro Field', 'Fairbanks', 'US');
insert into aeroporti (nome, citta, paese) values ('Canandaigua Airport', 'Ontario County IDA', 'US');
insert into aeroporti (nome, citta, paese) values ('Moro Airport', 'Moro', 'PG');
insert into aeroporti (nome, citta, paese) values ('Chichester/Goodwood Airport', 'Chichester', 'GB');
insert into aeroporti (nome, citta, paese) values ('Kings Creek Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Belfast International Airport', 'Belfast', 'GB');
insert into aeroporti (nome, citta, paese) values ('Rafsanjan Airport', null, 'IR');
insert into aeroporti (nome, citta, paese) values ('Springvale Airport', 'Springvale', 'AU');
insert into aeroporti (nome, citta, paese) values ('El Gora Airport', 'El Gora', 'EG');
insert into aeroporti (nome, citta, paese) values ('Yenkis(Yankisa) Airport', null, 'PG');
insert into aeroporti (nome, citta, paese) values ('Cortes Bay Water Aerodrome', 'Cortes Bay', 'CA');
insert into aeroporti (nome, citta, paese) values ('Cibeureum Airport', 'Tasikmalaya-Java Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Isle of Man Airport', 'Castletown', 'IM');
insert into aeroporti (nome, citta, paese) values ('Lady Elliot Island Airstrip', 'Lady Elliot Island', 'AU');
insert into aeroporti (nome, citta, paese) values ('Upiara Airport', 'Upiara', 'PG');
insert into aeroporti (nome, citta, paese) values ('Maple Bay Seaplane Base', 'Maple Bay', 'CA');
insert into aeroporti (nome, citta, paese) values ('Darchula Airport', 'Darchula', 'NP');
insert into aeroporti (nome, citta, paese) values ('Long Pasia Airport', 'Long Miau', 'MY');
insert into aeroporti (nome, citta, paese) values ('Adolfo Suárez Madrid–Barajas Airport', 'Madrid', 'ES');
insert into aeroporti (nome, citta, paese) values ('Yenkis(Yankisa) Airport', null, 'PG');
insert into aeroporti (nome, citta, paese) values ('Atlantic City International Airport', 'Atlantic City', 'US');
insert into aeroporti (nome, citta, paese) values ('Las Brujas Airport', 'Corozal', 'CO');
insert into aeroporti (nome, citta, paese) values ('Albacete-Los Llanos Airport', 'Albacete', 'ES');
insert into aeroporti (nome, citta, paese) values ('Corazón de Jesús Airport', 'Corazón de Jesús and Narganá Islands', 'PA');
insert into aeroporti (nome, citta, paese) values ('Madera Municipal Airport', 'Madera', 'US');
insert into aeroporti (nome, citta, paese) values ('Kigali International Airport', 'Kigali', 'RW');
insert into aeroporti (nome, citta, paese) values ('Aomori Airport', 'Aomori', 'JP');
insert into aeroporti (nome, citta, paese) values ('Perai Tepuy Airport', null, 'VE');
insert into aeroporti (nome, citta, paese) values ('Foothills Regional Airport', 'Morganton', 'US');
insert into aeroporti (nome, citta, paese) values ('Buluh Tumbang (H A S Hanandjoeddin) Airport', 'Tanjung Pandan-Belitung Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Faro Airport', 'Faro', 'PT');
insert into aeroporti (nome, citta, paese) values ('Breves Airport', 'Breves', 'BR');
insert into aeroporti (nome, citta, paese) values ('Tableland Homestead Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Diomício Freitas Airport', 'Criciúma', 'BR');
insert into aeroporti (nome, citta, paese) values ('Hamad International Airport', 'Doha', 'QA');
insert into aeroporti (nome, citta, paese) values ('Pryor Field Regional Airport', 'Decatur', 'US');
insert into aeroporti (nome, citta, paese) values ('Gelendzhik Airport', 'Gelendzhik', 'RU');
insert into aeroporti (nome, citta, paese) values ('Barra Airport', 'Barra', 'BR');
insert into aeroporti (nome, citta, paese) values ('Gewoia Airport', 'Gewoia', 'PG');
insert into aeroporti (nome, citta, paese) values ('South Naknek Nr 2 Airport', 'South Naknek', 'US');
insert into aeroporti (nome, citta, paese) values ('Ilam Airport', 'Ilam', 'IR');
insert into aeroporti (nome, citta, paese) values ('NASA Crows Landing Airport', 'Crows Landing', 'US');
insert into aeroporti (nome, citta, paese) values ('Anacortes Airport', 'Anacortes', 'US');
insert into aeroporti (nome, citta, paese) values ('Sahiwal Airport', 'Sahiwal', 'PK');
insert into aeroporti (nome, citta, paese) values ('Shanghai Hongqiao International Airport', 'Shanghai', 'CN');
insert into aeroporti (nome, citta, paese) values ('Sandnessjøen Airport (Stokka)', 'Alstahaug', 'NO');
insert into aeroporti (nome, citta, paese) values ('Santa Bárbara Airport', 'Iscuandé', 'CO');
insert into aeroporti (nome, citta, paese) values ('Senipah Heliport', 'Senipah', 'ID');
insert into aeroporti (nome, citta, paese) values ('Kristiansand Airport', 'Kjevik', 'NO');
insert into aeroporti (nome, citta, paese) values ('Arica Airport', 'Arica', 'CO');
insert into aeroporti (nome, citta, paese) values ('Kwethluk Airport', 'Kwethluk', 'US');
insert into aeroporti (nome, citta, paese) values ('Ilam Airport', 'Ilam', 'IR');
insert into aeroporti (nome, citta, paese) values ('Chengjisihan Airport', 'Zhalantun', 'CN');
insert into aeroporti (nome, citta, paese) values ('Jahrom Airport', 'Jahrom', 'IR');
insert into aeroporti (nome, citta, paese) values ('Al Asad Air Base', 'Hīt', 'IQ');
insert into aeroporti (nome, citta, paese) values ('Phnom Penh International Airport', 'Phnom Penh', 'KH');
insert into aeroporti (nome, citta, paese) values ('Bulgan Airport', 'Bulgan', 'MN');
insert into aeroporti (nome, citta, paese) values ('Etadunna Airport', 'Etadunna', 'AU');
insert into aeroporti (nome, citta, paese) values ('Merdei Airport', 'Merdei-Papua Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Koingnaas Airport', 'Koingnaas', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Macenta Airport', 'Macenta', 'GN');
insert into aeroporti (nome, citta, paese) values ('Tamchakett Airport', 'Tamchakett', 'MR');
insert into aeroporti (nome, citta, paese) values ('Suceava Stefan cel Mare Airport', 'Suceava', 'RO');
insert into aeroporti (nome, citta, paese) values ('Welshpool Airport', 'Welshpool', 'AU');
insert into aeroporti (nome, citta, paese) values ('Tucumã Airport', 'Tucumã', 'BR');
insert into aeroporti (nome, citta, paese) values ('Jiansanjiang Airport', 'Jiansanjiang', 'CN');
insert into aeroporti (nome, citta, paese) values ('Sishen Airport', 'Sishen', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Três Passos Airport', 'Três Passos', 'BR');
insert into aeroporti (nome, citta, paese) values ('Bartolomeu Lisandro Airport', 'Campos Dos Goytacazes', 'BR');
insert into aeroporti (nome, citta, paese) values ('Dr. Arturo H. Illia Airport', 'General Roca', 'AR');
insert into aeroporti (nome, citta, paese) values ('Taguatinga Airport', 'Taguatinga', 'BR');
insert into aeroporti (nome, citta, paese) values ('Valença Airport', 'Valença', 'BR');
insert into aeroporti (nome, citta, paese) values ('Tunggul Wulung Airport', 'Cilacap-Java Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Kota Kinabalu International Airport', 'Kota Kinabalu', 'MY');
insert into aeroporti (nome, citta, paese) values ('Hastings Airport', 'Freetown', 'SL');
insert into aeroporti (nome, citta, paese) values ('Philip Billard Municipal Airport', 'Topeka', 'US');
insert into aeroporti (nome, citta, paese) values ('Trois-Rivières Airport', 'Trois-Rivières', 'CA');
insert into aeroporti (nome, citta, paese) values ('Kirkland Lake Airport', 'Kirkland Lake', 'CA');
insert into aeroporti (nome, citta, paese) values ('Tacoma Narrows Airport', 'Tacoma', 'US');
insert into aeroporti (nome, citta, paese) values ('Washington County Airport', 'Washington', 'US');
insert into aeroporti (nome, citta, paese) values ('Gebe Airport', 'Gebe Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Patrocínio Airport', 'Patrocínio', 'BR');
insert into aeroporti (nome, citta, paese) values ('Suceava Stefan cel Mare Airport', 'Suceava', 'RO');
insert into aeroporti (nome, citta, paese) values ('Waterloo Regional Airport', 'Waterloo', 'US');
insert into aeroporti (nome, citta, paese) values ('Nordholz Naval Airbase', 'Cuxhaven', 'DE');
insert into aeroporti (nome, citta, paese) values ('Yelizovo Airport', 'Petropavlovsk-Kamchatsky', 'RU');
insert into aeroporti (nome, citta, paese) values ('Andulo Airport', null, 'AO');
insert into aeroporti (nome, citta, paese) values ('Afton Municipal Airport', 'Afton', 'US');
insert into aeroporti (nome, citta, paese) values ('Streaky Bay Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Muan International Airport', 'Piseo-ri (Muan)', 'KR');
insert into aeroporti (nome, citta, paese) values ('Bogorodskoye Airport', 'Bogorodskoye', 'RU');
insert into aeroporti (nome, citta, paese) values ('Rennes-Saint-Jacques Airport', 'Rennes/Saint-Jacques', 'FR');
insert into aeroporti (nome, citta, paese) values ('Baganga airport', 'Baganga', 'PH');
insert into aeroporti (nome, citta, paese) values ('Košice Airport', 'Košice', 'SK');
insert into aeroporti (nome, citta, paese) values ('Böblingen Flugfeld', 'Böblingen', 'DE');
insert into aeroporti (nome, citta, paese) values ('Buffalo Spring', 'Samburu', 'KE');
insert into aeroporti (nome, citta, paese) values ('Federico Garcia Lorca Airport', 'Granada', 'ES');
insert into aeroporti (nome, citta, paese) values ('Barra del Colorado Airport', 'Pococi', 'CR');
insert into aeroporti (nome, citta, paese) values ('Gujrat Airport', 'Gujrat', 'PK');
insert into aeroporti (nome, citta, paese) values ('Kosipe Airport', 'Kosipe Mission', 'PG');
insert into aeroporti (nome, citta, paese) values ('Shakawe Airport', 'Shakawe', 'BW');
insert into aeroporti (nome, citta, paese) values ('Anapa Vityazevo Airport', 'Anapa', 'RU');
insert into aeroporti (nome, citta, paese) values ('Moulay Ali Cherif Airport', 'Errachidia', 'MA');
insert into aeroporti (nome, citta, paese) values ('L''Espérance Airport', 'Grand Case', 'MF');
insert into aeroporti (nome, citta, paese) values ('Ayacucho Airport', 'Ayacucho', 'CO');
insert into aeroporti (nome, citta, paese) values ('Governor''s Harbour Airport', 'Governor''s Harbour', 'BS');
insert into aeroporti (nome, citta, paese) values ('Karonga Airport', 'Karonga', 'MW');
insert into aeroporti (nome, citta, paese) values ('Mahendranagar Airport', 'Mahendranagar', 'NP');
insert into aeroporti (nome, citta, paese) values ('Edwaki Airport', 'Yellow River Mission', 'PG');
insert into aeroporti (nome, citta, paese) values ('Masi Manimba Airport', 'Masi Manimba', 'CD');
insert into aeroporti (nome, citta, paese) values ('Catalão Airport', 'Catalão', 'BR');
insert into aeroporti (nome, citta, paese) values ('Browns Airport', 'Weeping Water', 'US');
insert into aeroporti (nome, citta, paese) values ('Ulyanovsk Baratayevka Airport', 'Ulyanovsk', 'RU');
insert into aeroporti (nome, citta, paese) values ('Perryville Airport', 'Perryville', 'US');
insert into aeroporti (nome, citta, paese) values ('Fuyun Koktokay Airport', 'Fuyun', 'CN');
insert into aeroporti (nome, citta, paese) values ('Lannion-Côte de Granit Airport', 'Lannion', 'FR');
insert into aeroporti (nome, citta, paese) values ('Anuha Island Resort Airport', 'Anhua Island', 'SB');
insert into aeroporti (nome, citta, paese) values ('De Kooy Airport', 'Den Helder', 'NL');
insert into aeroporti (nome, citta, paese) values ('Bertoua Airport', 'Bertoua', 'CM');
insert into aeroporti (nome, citta, paese) values ('São Jorge Airport', 'Velas', 'PT');
insert into aeroporti (nome, citta, paese) values ('Yeva Airport', 'Yeva', 'PG');
insert into aeroporti (nome, citta, paese) values ('Bandundu Airport', null, 'CD');
insert into aeroporti (nome, citta, paese) values ('Saint-Étienne-Bouthéon Airport', 'Saint-Étienne/Bouthéon', 'FR');
insert into aeroporti (nome, citta, paese) values ('Midgard Airport', 'Midgard', 'NA');
insert into aeroporti (nome, citta, paese) values ('Barrow County Airport', 'Winder', 'US');
insert into aeroporti (nome, citta, paese) values ('Buchanan Field', 'Concord', 'US');
insert into aeroporti (nome, citta, paese) values ('Lugano Airport', 'Lugano', 'CH');
insert into aeroporti (nome, citta, paese) values ('Westsound/Wsx Seaplane Base', 'Westsound', 'US');
insert into aeroporti (nome, citta, paese) values ('Ulithi Airport', 'Falalop Island', 'FM');
insert into aeroporti (nome, citta, paese) values ('Marechal Rondon Airport', 'Cuiabá', 'BR');
insert into aeroporti (nome, citta, paese) values ('Gambell Airport', 'Gambell', 'US');
insert into aeroporti (nome, citta, paese) values ('Kasba Lake Airport', 'Kasba Lake', 'CA');
insert into aeroporti (nome, citta, paese) values ('Sigiriya Air Force Base', 'Sigiriya', 'LK');
insert into aeroporti (nome, citta, paese) values ('China Strait Airstrip', 'Samarai Island', 'PG');
insert into aeroporti (nome, citta, paese) values ('Tulsipur Airport', 'Dang', 'NP');
insert into aeroporti (nome, citta, paese) values ('Robe Airport', 'Goba', 'ET');
insert into aeroporti (nome, citta, paese) values ('Malmstrom Air Force Base', 'Great Falls', 'US');
insert into aeroporti (nome, citta, paese) values ('Devonport Airport', 'Devonport', 'AU');
insert into aeroporti (nome, citta, paese) values ('Bawan Airport', null, 'PG');
insert into aeroporti (nome, citta, paese) values ('Croker Island Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Kooddoo Airport', 'Huvadhu Atoll', 'MV');
insert into aeroporti (nome, citta, paese) values ('Qaqortoq Heliport', 'Qaqortoq', 'GL');
insert into aeroporti (nome, citta, paese) values ('Chacalluta Airport', 'Arica', 'CL');
insert into aeroporti (nome, citta, paese) values ('Green River Municipal Airport', 'Green River', 'US');
insert into aeroporti (nome, citta, paese) values ('Mahdia Airport', 'Mahdia', 'GY');
insert into aeroporti (nome, citta, paese) values ('Pantnagar Airport', 'Pantnagar', 'IN');
insert into aeroporti (nome, citta, paese) values ('Willow Airport', 'Willow', 'US');
insert into aeroporti (nome, citta, paese) values ('Namudi Airport', 'Namudi', 'PG');
insert into aeroporti (nome, citta, paese) values ('Centralia Municipal Airport', 'Centralia', 'US');
insert into aeroporti (nome, citta, paese) values ('Riyadh Air Base', 'Riyadh', 'SA');
insert into aeroporti (nome, citta, paese) values ('Adi Sutjipto International Airport', 'Yogyakarta-Java Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Long Semado Airport', 'Long Semado', 'MY');
insert into aeroporti (nome, citta, paese) values ('RAF West Malling', 'West Malling', 'GB');
insert into aeroporti (nome, citta, paese) values ('La Roche-sur-Yon Airport', 'La Roche-sur-Yon/Les Ajoncs', 'FR');
insert into aeroporti (nome, citta, paese) values ('Lianyungang Airport', 'Lianyungang', 'CN');
insert into aeroporti (nome, citta, paese) values ('Rewa Airport, Chorhata, REWA', 'Rewa', 'IN');
insert into aeroporti (nome, citta, paese) values ('Katowice International Airport', 'Katowice', 'PL');
insert into aeroporti (nome, citta, paese) values ('Sydney Bankstown Airport', 'Sydney', 'AU');
insert into aeroporti (nome, citta, paese) values ('Porter County Municipal Airport', 'Valparaiso', 'US');
insert into aeroporti (nome, citta, paese) values ('Theodore Francis Green State Airport', 'Providence', 'US');
insert into aeroporti (nome, citta, paese) values ('Colonia Catriel Airport', 'Colonia Catriel', 'AR');
insert into aeroporti (nome, citta, paese) values ('Dalanzadgad Airport', 'Dalanzadgad', 'MN');
insert into aeroporti (nome, citta, paese) values ('Daniel K Inouye International Airport', 'Honolulu', 'US');
insert into aeroporti (nome, citta, paese) values ('Area De Material Airport', 'Rio Cuarto', 'AR');
insert into aeroporti (nome, citta, paese) values ('Sir Abubakar Tafawa Balewa International Airport', 'Bauchi', 'NG');
insert into aeroporti (nome, citta, paese) values ('Fort Nelson Airport', 'Fort Nelson', 'CA');
insert into aeroporti (nome, citta, paese) values ('Parma Airport', 'Parma', 'IT');
insert into aeroporti (nome, citta, paese) values ('Hon Airport', null, 'LY');
insert into aeroporti (nome, citta, paese) values ('Tan Son Nhat International Airport', 'Ho Chi Minh City', 'VN');
insert into aeroporti (nome, citta, paese) values ('Lázaro Cárdenas Airport', 'Lázaro Cárdenas', 'MX');
insert into aeroporti (nome, citta, paese) values ('Stokmarknes Skagen Airport', 'Hadsel', 'NO');
insert into aeroporti (nome, citta, paese) values ('Capital City Airport', 'Lansing', 'US');
insert into aeroporti (nome, citta, paese) values ('Deering Airport', 'Deering', 'US');
insert into aeroporti (nome, citta, paese) values ('Salina Gunnison Airport', 'Salina', 'US');
insert into aeroporti (nome, citta, paese) values ('Longdongbao Airport', 'Guiyang', 'CN');
insert into aeroporti (nome, citta, paese) values ('Ngot Nzoungou Airport', 'Dolisie', 'CG');
insert into aeroporti (nome, citta, paese) values ('Simon Mwansa Kapwepwe International Airport', 'Ndola', 'ZM');
insert into aeroporti (nome, citta, paese) values ('Telegraph Creek Airport', 'Telegraph Creek', 'CA');
insert into aeroporti (nome, citta, paese) values ('St Augustin Airport', 'St-Augustin', 'CA');
insert into aeroporti (nome, citta, paese) values ('Matão Airport', 'Matão', 'BR');
insert into aeroporti (nome, citta, paese) values ('Nakina Airport', 'Nakina', 'CA');
insert into aeroporti (nome, citta, paese) values ('Elfin Cove Seaplane Base', 'Elfin Cove', 'US');
insert into aeroporti (nome, citta, paese) values ('Oakey Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Pulau Pangkor Airport', 'Pangkor Island', 'MY');
insert into aeroporti (nome, citta, paese) values ('Gunnison Crested Butte Regional Airport', 'Gunnison', 'US');
insert into aeroporti (nome, citta, paese) values ('Barkley Regional Airport', 'Paducah', 'US');
insert into aeroporti (nome, citta, paese) values ('Mamitupo Airport', 'Mamitupo', 'PA');
insert into aeroporti (nome, citta, paese) values ('Narrandera Airport', 'Narrandera', 'AU');
insert into aeroporti (nome, citta, paese) values ('Mukeiras Airport', 'Mukayras', 'YE');
insert into aeroporti (nome, citta, paese) values ('Toowoomba Wellcamp Airport', 'Toowoomba', 'AU');
insert into aeroporti (nome, citta, paese) values ('Lusikisiki Airport', 'Lusikisiki', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Gunnedah Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Mae Hong Son Airport', 'Mae Hong Son', 'TH');
insert into aeroporti (nome, citta, paese) values ('Dalton Municipal Airport', 'Dalton', 'US');
insert into aeroporti (nome, citta, paese) values ('Maria Reiche Neuman Airport', 'Nazca', 'PE');
insert into aeroporti (nome, citta, paese) values ('West Bend Municipal Airport', 'West Bend', 'US');
insert into aeroporti (nome, citta, paese) values ('Keningau Airport', 'Keningau', 'MY');
insert into aeroporti (nome, citta, paese) values ('Namudi Airport', 'Namudi', 'PG');
insert into aeroporti (nome, citta, paese) values ('Gao Airport', null, 'ML');
insert into aeroporti (nome, citta, paese) values ('Stony River 2 Airport', 'Stony River', 'US');
insert into aeroporti (nome, citta, paese) values ('Priština International Airport', 'Prishtina', 'XK');
insert into aeroporti (nome, citta, paese) values ('Bildudalur Airport', 'Bildudalur', 'IS');
insert into aeroporti (nome, citta, paese) values ('Rio Grande Airport', 'Rio Grande', 'BR');
insert into aeroporti (nome, citta, paese) values ('Martinique Aimé Césaire International Airport', 'Fort-de-France', 'MQ');
insert into aeroporti (nome, citta, paese) values ('Moala Airport', 'Moala', 'FJ');
insert into aeroporti (nome, citta, paese) values ('Vir Savarkar International Airport', 'Port Blair', 'IN');
insert into aeroporti (nome, citta, paese) values ('Hotan Airport', 'Hotan', 'CN');
insert into aeroporti (nome, citta, paese) values ('Gratiot Community Airport', 'Alma', 'US');
insert into aeroporti (nome, citta, paese) values ('Bob Sikes Airport', 'Crestview', 'US');
insert into aeroporti (nome, citta, paese) values ('Victoria Reservoir Seaplane Base', 'Kandy', 'LK');
insert into aeroporti (nome, citta, paese) values ('Kimaam Airport', 'Kimaam', 'ID');
insert into aeroporti (nome, citta, paese) values ('Tidjikja Airport', 'Tidjikja', 'MR');
insert into aeroporti (nome, citta, paese) values ('Searle Field', 'Ogallala', 'US');
insert into aeroporti (nome, citta, paese) values ('Pampulha - Carlos Drummond de Andrade Airport', 'Belo Horizonte', 'BR');
insert into aeroporti (nome, citta, paese) values ('Indianapolis International Airport', 'Indianapolis', 'US');
insert into aeroporti (nome, citta, paese) values ('Khajuraho Airport', 'Khajuraho', 'IN');
insert into aeroporti (nome, citta, paese) values ('Aspen-Pitkin Co/Sardy Field', 'Aspen', 'US');
insert into aeroporti (nome, citta, paese) values ('Phan Rang Airport', 'Phan Rang', 'VN');
insert into aeroporti (nome, citta, paese) values ('Salina Municipal Airport', 'Salina', 'US');
insert into aeroporti (nome, citta, paese) values ('General Mitchell International Airport', 'Milwaukee', 'US');
insert into aeroporti (nome, citta, paese) values ('El Embrujo Airport', 'Providencia', 'CO');
insert into aeroporti (nome, citta, paese) values ('Qeshm International Airport', 'Qeshm', 'IR');
insert into aeroporti (nome, citta, paese) values ('Karonga Airport', 'Karonga', 'MW');
insert into aeroporti (nome, citta, paese) values ('Sault Ste Marie Airport', 'Sault Ste Marie', 'CA');
insert into aeroporti (nome, citta, paese) values ('Senai International Airport', 'Johor Bahru', 'MY');
insert into aeroporti (nome, citta, paese) values ('Kanabea Airport', 'Kanabea', 'PG');
insert into aeroporti (nome, citta, paese) values ('Malta Airport', 'Malta', 'US');
insert into aeroporti (nome, citta, paese) values ('Omar N Bradley Airport', 'Moberly', 'US');
insert into aeroporti (nome, citta, paese) values ('Ilam Airport', 'Ilam', 'IR');
insert into aeroporti (nome, citta, paese) values ('Bhojpur Airport', 'Bhojpur', 'NP');
insert into aeroporti (nome, citta, paese) values ('Tamale Airport', 'Tamale', 'GH');
insert into aeroporti (nome, citta, paese) values ('Ingalls Field', 'Hot Springs', 'US');
insert into aeroporti (nome, citta, paese) values ('Lubbock Preston Smith International Airport', 'Lubbock', 'US');
insert into aeroporti (nome, citta, paese) values ('Mati National Airport', 'Mati', 'PH');
insert into aeroporti (nome, citta, paese) values ('Port Bailey Seaplane Base', 'Port Bailey', 'US');
insert into aeroporti (nome, citta, paese) values ('Manley Hot Springs Airport', 'Manley Hot Springs', 'US');
insert into aeroporti (nome, citta, paese) values ('Mackinac Island Airport', 'Mackinac Island', 'US');
insert into aeroporti (nome, citta, paese) values ('Kirkuk Air Base', 'Kirkuk', 'IQ');
insert into aeroporti (nome, citta, paese) values ('Shangjie Airport', 'Zhengzhou', 'CN');
insert into aeroporti (nome, citta, paese) values ('M. R. Štefánik Airport', 'Bratislava', 'SK');
insert into aeroporti (nome, citta, paese) values ('Sunyani Airport', 'Sunyani', 'GH');
insert into aeroporti (nome, citta, paese) values ('Dillon Airport', 'Dillon', 'US');
insert into aeroporti (nome, citta, paese) values ('South Bimini Airport', 'South Bimini', 'BS');
insert into aeroporti (nome, citta, paese) values ('Tri-Cities Regional TN/VA Airport', 'Bristol/Johnson/Kingsport', 'US');
insert into aeroporti (nome, citta, paese) values ('Captain Ramon Xatruch Airport', 'La Palma', 'PA');
insert into aeroporti (nome, citta, paese) values ('San Antonio International Airport', 'San Antonio', 'US');
insert into aeroporti (nome, citta, paese) values ('Kumejima Airport', null, 'JP');
insert into aeroporti (nome, citta, paese) values ('Owando Airport', 'Owando', 'CG');
insert into aeroporti (nome, citta, paese) values ('Alonso Valderrama Airport', 'Chitré', 'PA');
insert into aeroporti (nome, citta, paese) values ('Komatipoort Airport', 'Komatipoort', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Ambunti Airport', 'Ambunti', 'PG');
insert into aeroporti (nome, citta, paese) values ('Fort Albany Airport', 'Fort Albany', 'CA');
insert into aeroporti (nome, citta, paese) values ('Januária Airport', 'Januária', 'BR');
insert into aeroporti (nome, citta, paese) values ('Porto dos Gaúchos Airport', 'Porto Dos Gaúchos', 'BR');
insert into aeroporti (nome, citta, paese) values ('Hihifo Airport', 'Wallis Island', 'WF');
insert into aeroporti (nome, citta, paese) values ('Petrozavodsk Airport', 'Petrozavodsk', 'RU');
insert into aeroporti (nome, citta, paese) values ('Chulman Airport', 'Neryungri', 'RU');
insert into aeroporti (nome, citta, paese) values ('Ben Slimane Airport', 'Ben Slimane', 'MA');
insert into aeroporti (nome, citta, paese) values ('Cholet Le Pontreau Airport', 'Cholet/Le Pontreau', 'FR');
insert into aeroporti (nome, citta, paese) values ('Mobile Downtown Airport', 'Mobile', 'US');
insert into aeroporti (nome, citta, paese) values ('Rankin Inlet Airport', 'Rankin Inlet', 'CA');
insert into aeroporti (nome, citta, paese) values ('Kingscote Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Piloto Osvaldo Marques Dias Airport', 'Alta Floresta', 'BR');
insert into aeroporti (nome, citta, paese) values ('Pond Inlet Airport', 'Pond Inlet', 'CA');
insert into aeroporti (nome, citta, paese) values ('Umbu Mehang Kunda Airport', 'Waingapu-Sumba Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Mopti Airport', null, 'ML');
insert into aeroporti (nome, citta, paese) values ('Porto Amboim Airport', 'Port Amboim', 'AO');
insert into aeroporti (nome, citta, paese) values ('Ozona Municipal Airport', 'Ozona', 'US');
insert into aeroporti (nome, citta, paese) values ('Homer Airport', 'Homer', 'US');
insert into aeroporti (nome, citta, paese) values ('Gove Airport', 'Nhulunbuy', 'AU');
insert into aeroporti (nome, citta, paese) values ('Ifuru Airport', 'Ifuru Island', 'MV');
insert into aeroporti (nome, citta, paese) values ('Agatti Airport', null, 'IN');
insert into aeroporti (nome, citta, paese) values ('Maria Reiche Neuman Airport', 'Nazca', 'PE');
insert into aeroporti (nome, citta, paese) values ('Yuanmou Air Base', 'Yuanmou', 'CN');
insert into aeroporti (nome, citta, paese) values ('Fundación Airport', 'Fundación', 'CO');
insert into aeroporti (nome, citta, paese) values ('Nadym Airport', 'Nadym', 'RU');
insert into aeroporti (nome, citta, paese) values ('Port Keats Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Colmar-Houssen Airport', 'Colmar/Houssen', 'FR');
insert into aeroporti (nome, citta, paese) values ('Austin Robert Mueller Municipal', null, 'US');
insert into aeroporti (nome, citta, paese) values ('Easton State Airport', 'Easton', 'US');
insert into aeroporti (nome, citta, paese) values ('Monterrey Airport', 'Monterrey', 'CO');
insert into aeroporti (nome, citta, paese) values ('Hosea Kutako International Airport', 'Windhoek', 'NA');
insert into aeroporti (nome, citta, paese) values ('Palenque International Airport', null, 'MX');
insert into aeroporti (nome, citta, paese) values ('Værøy Heliport', 'Værøy', 'NO');
insert into aeroporti (nome, citta, paese) values ('Shigatse Air Base', 'Xigazê', 'CN');
insert into aeroporti (nome, citta, paese) values ('Likoma Island Airport', 'Likoma Island', 'MW');
insert into aeroporti (nome, citta, paese) values ('Sion Airport', 'Sion', 'CH');
insert into aeroporti (nome, citta, paese) values ('Los Cerrillos Airport', 'Santiago', 'CL');
insert into aeroporti (nome, citta, paese) values ('Las Malvinas/Echarate Airport', 'Las Malvinas', 'PE');
insert into aeroporti (nome, citta, paese) values ('Nuiqsut Airport', 'Nuiqsut', 'US');
insert into aeroporti (nome, citta, paese) values ('Prince Rupert/Seal Cove Seaplane Base', null, 'CA');
insert into aeroporti (nome, citta, paese) values ('Cataratas Del Iguazú International Airport', 'Puerto Iguazu', 'AR');
insert into aeroporti (nome, citta, paese) values ('Geladi Airport', 'Geladi', 'ET');
insert into aeroporti (nome, citta, paese) values ('Celaque Airport', 'Gracias', 'HN');
insert into aeroporti (nome, citta, paese) values ('Siuna', 'Siuna', 'NI');
insert into aeroporti (nome, citta, paese) values ('Lipetsk Airport', 'Lipetsk', 'RU');
insert into aeroporti (nome, citta, paese) values ('Chitato Airport', 'Chitato', 'AO');
insert into aeroporti (nome, citta, paese) values ('Banmaw Airport', 'Banmaw', 'MM');
insert into aeroporti (nome, citta, paese) values ('Shaxian Airport', 'Sanming', 'CN');
insert into aeroporti (nome, citta, paese) values ('Béziers-Vias Airport', 'Béziers/Vias', 'FR');
insert into aeroporti (nome, citta, paese) values ('Reggio Calabria Airport', 'Reggio Calabria', 'IT');
insert into aeroporti (nome, citta, paese) values ('Babo Airport', 'Babo-Papua Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('San Nicolas De Bari Airport', 'San Nicolás', 'CU');
insert into aeroporti (nome, citta, paese) values ('Chipinge Airport', 'Chipinge', 'ZW');
insert into aeroporti (nome, citta, paese) values ('Sola Airport', 'Sola', 'VU');
insert into aeroporti (nome, citta, paese) values ('Méndez Airport', 'Santiago de Méndez', 'EC');
insert into aeroporti (nome, citta, paese) values ('Cherrabah Airport', 'Cherrabah Homestead Resort', 'AU');
insert into aeroporti (nome, citta, paese) values ('William P Hobby Airport', 'Houston', 'US');
insert into aeroporti (nome, citta, paese) values ('Leirin Airport', null, 'NO');
insert into aeroporti (nome, citta, paese) values ('Lee Gilmer Memorial Airport', 'Gainesville', 'US');
insert into aeroporti (nome, citta, paese) values ('Komako Airport', 'Komako', 'PG');
insert into aeroporti (nome, citta, paese) values ('Tableland Homestead Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('San Diego International Airport', 'San Diego', 'US');
insert into aeroporti (nome, citta, paese) values ('Franklin County Airport', 'Sewanee', 'US');
insert into aeroporti (nome, citta, paese) values ('Barcelos Airport', 'Barcelos', 'BR');
insert into aeroporti (nome, citta, paese) values ('Shashi Airport', 'Shashi', 'CN');
insert into aeroporti (nome, citta, paese) values ('Palonegro Airport', 'Bucaramanga', 'CO');
insert into aeroporti (nome, citta, paese) values ('Makurdi Airport', 'Makurdi', 'NG');
insert into aeroporti (nome, citta, paese) values ('Gamboa Airport', 'Castro', 'CL');
insert into aeroporti (nome, citta, paese) values ('Catarman National Airport', 'Catarman', 'PH');
insert into aeroporti (nome, citta, paese) values ('Tibú Airport', 'Tibú', 'CO');
insert into aeroporti (nome, citta, paese) values ('Aldan Airport', 'Aldan', 'RU');
insert into aeroporti (nome, citta, paese) values ('Kornasoren Airfield', 'Kornasoren-Numfoor Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Calvi-Sainte-Catherine Airport', 'Calvi/Sainte-Catherine', 'FR');
insert into aeroporti (nome, citta, paese) values ('Bydgoszcz Ignacy Jan Paderewski Airport', 'Bydgoszcz', 'PL');
insert into aeroporti (nome, citta, paese) values ('Gora Airstrip', 'Gora', 'PG');
insert into aeroporti (nome, citta, paese) values ('Great Falls International Airport', 'Great Falls', 'US');
insert into aeroporti (nome, citta, paese) values ('Kaiapit Airport', 'Kaiapit', 'PG');
insert into aeroporti (nome, citta, paese) values ('Mulia Airport', 'Mulia-Papua Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('New Moon Airport', 'Basalt', 'AU');
insert into aeroporti (nome, citta, paese) values ('A L Mangham Jr. Regional Airport', 'Nacogdoches', 'US');
insert into aeroporti (nome, citta, paese) values ('Sanya Phoenix International Airport', 'Sanya', 'CN');
insert into aeroporti (nome, citta, paese) values ('Sumbawa Besar Airport', 'Sumbawa Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Bollon Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Campo Grande Airport', 'Campo Grande', 'BR');
insert into aeroporti (nome, citta, paese) values ('Ronald Reagan Washington National Airport', 'Washington', 'US');
insert into aeroporti (nome, citta, paese) values ('Caransebeş Airport', 'Caransebeş', 'RO');
insert into aeroporti (nome, citta, paese) values ('Maribor Airport', null, 'SI');
insert into aeroporti (nome, citta, paese) values ('Olsztyn-Mazury Airport', 'Olsztyn', 'PL');
insert into aeroporti (nome, citta, paese) values ('Brussels South Charleroi Airport', 'Brussels', 'BE');
insert into aeroporti (nome, citta, paese) values ('Kaben Airport', 'Kaben', 'MH');
insert into aeroporti (nome, citta, paese) values ('Jimma Airport', 'Jimma', 'ET');
insert into aeroporti (nome, citta, paese) values ('Huangyan Luqiao Airport', 'Huangyan', 'CN');
insert into aeroporti (nome, citta, paese) values ('Brevig Mission Airport', 'Brevig Mission', 'US');
insert into aeroporti (nome, citta, paese) values ('Maupiti Airport', null, 'PF');
insert into aeroporti (nome, citta, paese) values ('Lauro Carneiro de Loyola Airport', 'Joinville', 'BR');
insert into aeroporti (nome, citta, paese) values ('Po Airport', 'Po', 'BF');
insert into aeroporti (nome, citta, paese) values ('Shashi Airport', 'Shashi', 'CN');
insert into aeroporti (nome, citta, paese) values ('Amado Nervo National Airport', 'Tepic', 'MX');
insert into aeroporti (nome, citta, paese) values ('La Grande-4 Airport', 'La Grande-4', 'CA');
insert into aeroporti (nome, citta, paese) values ('Brigadeiro Camarão Airport', 'Vilhena', 'BR');
insert into aeroporti (nome, citta, paese) values ('Flensburg-Schäferhaus Airport', 'Flensburg', 'DE');
insert into aeroporti (nome, citta, paese) values ('Victoria Airport', 'Victoria', 'CL');
insert into aeroporti (nome, citta, paese) values ('Monte Carmelo Airport', 'Monte Carmelo', 'BR');
insert into aeroporti (nome, citta, paese) values ('Asaba International Airport', 'Asaba', 'NG');
insert into aeroporti (nome, citta, paese) values ('Greenville Downtown Airport', 'Greenville', 'US');
insert into aeroporti (nome, citta, paese) values ('Gambella Airport', 'Gambela', 'ET');
insert into aeroporti (nome, citta, paese) values ('Pensacola Naval Air Station/Forrest Sherman Field', 'Pensacola', 'US');
insert into aeroporti (nome, citta, paese) values ('Tabora Airport', 'Tabora', 'TZ');
insert into aeroporti (nome, citta, paese) values ('Salina Cruz Naval Air Station', 'Salina Cruz', 'MX');
insert into aeroporti (nome, citta, paese) values ('Poplar Bluff Municipal Airport', 'Poplar Bluff', 'US');
insert into aeroporti (nome, citta, paese) values ('Manners Creek Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Ciudad Constitución Airport', 'Ciudad Constitución', 'MX');
insert into aeroporti (nome, citta, paese) values ('Shinyanga Airport', 'Shinyanga', 'TZ');
insert into aeroporti (nome, citta, paese) values ('Maryborough Airport', 'Maryborough', 'AU');
insert into aeroporti (nome, citta, paese) values ('Red Sucker Lake Airport', 'Red Sucker Lake', 'CA');
insert into aeroporti (nome, citta, paese) values ('Northwest Alabama Regional Airport', 'Muscle Shoals', 'US');
insert into aeroporti (nome, citta, paese) values ('Capitán Av. Salvador Ogaya G. airport', 'Puerto Suárez', 'BO');
insert into aeroporti (nome, citta, paese) values ('Cessna Aircraft Field', 'Wichita', 'US');
insert into aeroporti (nome, citta, paese) values ('Tambillos Airport', 'Coquimbo', 'CL');
insert into aeroporti (nome, citta, paese) values ('Hola Airport', 'Hola', 'KE');
insert into aeroporti (nome, citta, paese) values ('Kobe Airport', 'Kobe', 'JP');
insert into aeroporti (nome, citta, paese) values ('Mc Carthy Airport', 'Mccarthy', 'US');
insert into aeroporti (nome, citta, paese) values ('EuroAirport Basel-Mulhouse-Freiburg Airport', 'Bâle/Mulhouse', 'FR');
insert into aeroporti (nome, citta, paese) values ('Turlatovo Airport', 'Ryazan', 'RU');
insert into aeroporti (nome, citta, paese) values ('Licenciado Adolfo Lopez Mateos International Airport', 'Toluca', 'MX');
insert into aeroporti (nome, citta, paese) values ('RAF Lakenheath', 'Lakenheath', 'GB');
insert into aeroporti (nome, citta, paese) values ('Torembi Airport', 'Torembi', 'PG');
insert into aeroporti (nome, citta, paese) values ('Mota Lava Airport', 'Ablow', 'VU');
insert into aeroporti (nome, citta, paese) values ('Erechim Airport', 'Erechim', 'BR');
insert into aeroporti (nome, citta, paese) values ('Engati Airstrip', 'Engati', 'PG');
insert into aeroporti (nome, citta, paese) values ('Olbia Costa Smeralda Airport', 'Olbia (SS)', 'IT');
insert into aeroporti (nome, citta, paese) values ('Luabo Airport', 'Luabo', 'MZ');
insert into aeroporti (nome, citta, paese) values ('Batna Airport', 'Batna', 'DZ');
insert into aeroporti (nome, citta, paese) values ('Barrow Island Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('La Abraq Airport', 'Al Bayda''', 'LY');
insert into aeroporti (nome, citta, paese) values ('Boulder City Municipal Airport', 'Boulder City', 'US');
insert into aeroporti (nome, citta, paese) values ('El Debba Airport', 'El Debba', 'SD');
insert into aeroporti (nome, citta, paese) values ('Stephenville Clark Regional Airport', 'Stephenville', 'US');
insert into aeroporti (nome, citta, paese) values ('Abresso Airport', 'Ransiki-Papua Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Alferez Armando Rodriguez Airport', 'Las Lomitas', 'AR');
insert into aeroporti (nome, citta, paese) values ('Whitehouse Naval Outlying Field', 'Jacksonville', 'US');
insert into aeroporti (nome, citta, paese) values ('Helgoland-Düne Airport', 'Helgoland', 'DE');
insert into aeroporti (nome, citta, paese) values ('San Fernando De Apure Airport', 'Inglaterra', 'VE');
insert into aeroporti (nome, citta, paese) values ('Sacramento Mather Airport', 'Sacramento', 'US');
insert into aeroporti (nome, citta, paese) values ('Palm Beach International Airport', 'West Palm Beach', 'US');
insert into aeroporti (nome, citta, paese) values ('Kryvyi Rih International Airport', 'Kryvyi Rih', 'UA');
insert into aeroporti (nome, citta, paese) values ('Bydgoszcz Ignacy Jan Paderewski Airport', 'Bydgoszcz', 'PL');
insert into aeroporti (nome, citta, paese) values ('Hearst René Fontaine Municipal Airport', 'Hearst', 'CA');
insert into aeroporti (nome, citta, paese) values ('Saúl Airport', 'Saúl', 'GF');
insert into aeroporti (nome, citta, paese) values ('Raba Raba Airport', 'Rabaraba', 'PG');
insert into aeroporti (nome, citta, paese) values ('Tampa Padang Airport', 'Mamuju-Celebes Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Pine Island Airport', 'Corolla', 'US');
insert into aeroporti (nome, citta, paese) values ('Chileka International Airport', 'Blantyre', 'MW');
insert into aeroporti (nome, citta, paese) values ('Port Macquarie Airport', 'Port Macquarie', 'AU');
insert into aeroporti (nome, citta, paese) values ('Norwood Memorial Airport', 'Norwood', 'US');
insert into aeroporti (nome, citta, paese) values ('Ioannis Kapodistrias International Airport', 'Kerkyra Island', 'GR');
insert into aeroporti (nome, citta, paese) values ('Berlin-Tegel Airport', 'Berlin', 'DE');
insert into aeroporti (nome, citta, paese) values ('Vitebsk Vostochny Airport', 'Vitebsk', 'BY');
insert into aeroporti (nome, citta, paese) values ('Beslan Airport', 'Beslan', 'RU');
insert into aeroporti (nome, citta, paese) values ('Compton Woodley Airport', 'Compton', 'US');
insert into aeroporti (nome, citta, paese) values ('Handan Airport', 'Handan', 'CN');
insert into aeroporti (nome, citta, paese) values ('Manetai Airport', 'Manetai', 'PG');
insert into aeroporti (nome, citta, paese) values ('Kokoda Airport', 'Kokoda', 'PG');
insert into aeroporti (nome, citta, paese) values ('Bangassou Airport', 'Bangassou', 'CF');
insert into aeroporti (nome, citta, paese) values ('Kabalo Airport', 'Kabalo', 'CD');
insert into aeroporti (nome, citta, paese) values ('Chu Lai International Airport', 'Dung Quat Bay', 'VN');
insert into aeroporti (nome, citta, paese) values ('Jackpot Airport/Hayden Field', 'Jackpot', 'US');
insert into aeroporti (nome, citta, paese) values ('Piatã Airport', 'Piatã', 'BR');
insert into aeroporti (nome, citta, paese) values ('Hope Vale Airport', 'Hope Vale', 'AU');
insert into aeroporti (nome, citta, paese) values ('Redding Municipal Airport', 'Redding', 'US');
insert into aeroporti (nome, citta, paese) values ('Karato Airport', 'Karato', 'PG');
insert into aeroporti (nome, citta, paese) values ('Tulsa International Airport', 'Tulsa', 'US');
insert into aeroporti (nome, citta, paese) values ('Šiauliai International Airport', 'Šiauliai', 'LT');
insert into aeroporti (nome, citta, paese) values ('Sidney Municipal Airport', 'Sidney', 'US');
insert into aeroporti (nome, citta, paese) values ('Coban Airport', 'Coban', 'GT');
insert into aeroporti (nome, citta, paese) values ('Baker Lake Airport', 'Baker Lake', 'CA');
insert into aeroporti (nome, citta, paese) values ('Kitee Airport', null, 'FI');
insert into aeroporti (nome, citta, paese) values ('Bloodvein River Airport', 'Bloodvein River', 'CA');
insert into aeroporti (nome, citta, paese) values ('Trujillo Airport', 'Trujillo', 'HN');
insert into aeroporti (nome, citta, paese) values ('RAF Marham', 'Marham', 'GB');
insert into aeroporti (nome, citta, paese) values ('Glenormiston Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Oeiras Airport', 'Oeiras', 'BR');
insert into aeroporti (nome, citta, paese) values ('Nissan Island Airport', 'Nissan Island', 'PG');
insert into aeroporti (nome, citta, paese) values ('Sønderborg Airport', 'Sønderborg', 'DK');
insert into aeroporti (nome, citta, paese) values ('Kangding Airport', 'Kangding', 'CN');
insert into aeroporti (nome, citta, paese) values ('Åre Östersund Airport', 'Östersund', 'SE');
insert into aeroporti (nome, citta, paese) values ('Bensbach Airport', 'Bensbach', 'PG');
insert into aeroporti (nome, citta, paese) values ('Boeing Field King County International Airport', 'Seattle', 'US');
insert into aeroporti (nome, citta, paese) values ('Engati Airstrip', 'Engati', 'PG');
insert into aeroporti (nome, citta, paese) values ('Kikai Airport', 'Kikai', 'JP');
insert into aeroporti (nome, citta, paese) values ('Hendrik Van Eck Airport', 'Phalaborwa', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Dongara Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Jérémie Airport', 'Jeremie', 'HT');
insert into aeroporti (nome, citta, paese) values ('Bartow Municipal Airport', 'Bartow', 'US');
insert into aeroporti (nome, citta, paese) values ('Kingfisher Lake Airport', 'Kingfisher Lake', 'CA');
insert into aeroporti (nome, citta, paese) values ('Mostaganem Airport', null, 'DZ');
insert into aeroporti (nome, citta, paese) values ('Albertus Airport', 'Freeport', 'US');
insert into aeroporti (nome, citta, paese) values ('Drake Bay Airport', 'Puntarenas', 'CR');
insert into aeroporti (nome, citta, paese) values ('Lebakeng Airport', 'Lebakeng', 'LS');
insert into aeroporti (nome, citta, paese) values ('Yagoua Airport', 'Yagoua', 'CM');
insert into aeroporti (nome, citta, paese) values ('Dabra Airport', 'Dabra-Papua Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Pakhokku Airport', 'Pakhokku', 'MM');
insert into aeroporti (nome, citta, paese) values ('Pointe-à-Pitre Le Raizet', 'Pointe-à-Pitre', 'GP');
insert into aeroporti (nome, citta, paese) values ('Phrae Airport', null, 'TH');
insert into aeroporti (nome, citta, paese) values ('Truscott-Mungalalu Airport', 'Anjo Peninsula', 'AU');
insert into aeroporti (nome, citta, paese) values ('Naples Municipal Airport', 'Naples', 'US');
insert into aeroporti (nome, citta, paese) values ('Helena Regional Airport', 'Helena', 'US');
insert into aeroporti (nome, citta, paese) values ('Atlantic Municipal Airport', 'Atlantic', 'US');
insert into aeroporti (nome, citta, paese) values ('Sabu-Tardanu Airport', 'Sabu-Sawu Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Taguatinga Airport', 'Taguatinga', 'BR');
insert into aeroporti (nome, citta, paese) values ('Kalabo Airport', 'Kalabo', 'ZM');
insert into aeroporti (nome, citta, paese) values ('Syktyvkar Airport', 'Syktyvkar', 'RU');
insert into aeroporti (nome, citta, paese) values ('Nogales International Airport', null, 'MX');
insert into aeroporti (nome, citta, paese) values ('Sumbawa Besar Airport', 'Sumbawa Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Awang Airport', 'Cotabato City', 'PH');
insert into aeroporti (nome, citta, paese) values ('Qacha''s Nek Airport', 'Qacha''s Nek', 'LS');
insert into aeroporti (nome, citta, paese) values ('Faisalabad International Airport', 'Faisalabad', 'PK');
insert into aeroporti (nome, citta, paese) values ('Fort Smith Airport', 'Fort Smith', 'CA');
insert into aeroporti (nome, citta, paese) values ('Guajará-Mirim Airport', 'Guajará-Mirim', 'BR');
insert into aeroporti (nome, citta, paese) values ('St Angelo Airport', 'Enniskillen', 'GB');
insert into aeroporti (nome, citta, paese) values ('Minangkabau International Airport', 'Ketaping/Padang - Sumatra Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Syukuran Aminuddin Amir Airport', 'Luwok - Celebes Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Wasua Airport', 'Wasua', 'PG');
insert into aeroporti (nome, citta, paese) values ('Rio Claro Airport', 'Rio Claro', 'BR');
insert into aeroporti (nome, citta, paese) values ('Winnemucca Municipal Airport', 'Winnemucca', 'US');
insert into aeroporti (nome, citta, paese) values ('Napuka Island Airport', 'Napuka Island', 'PF');
insert into aeroporti (nome, citta, paese) values ('Bossangoa Airport', 'Bossangoa', 'CF');
insert into aeroporti (nome, citta, paese) values ('Gwinnett County Briscoe Field', 'Lawrenceville', 'US');
insert into aeroporti (nome, citta, paese) values ('Nkongsamba Airport', 'Nkongsamba', 'CM');
insert into aeroporti (nome, citta, paese) values ('Seshutes Airport', 'Seshutes', 'LS');
insert into aeroporti (nome, citta, paese) values ('Munduku Airport', 'Munduku', 'PG');
insert into aeroporti (nome, citta, paese) values ('McArthur River Mine Airport', 'McArthur River Mine', 'AU');
insert into aeroporti (nome, citta, paese) values ('Sila Airport', 'Sila Mission', 'PG');
insert into aeroporti (nome, citta, paese) values ('Agostinho Neto Airport', 'Ponta do Sol', 'CV');
insert into aeroporti (nome, citta, paese) values ('Bryansk Airport', 'Bryansk', 'RU');
insert into aeroporti (nome, citta, paese) values ('Maria Montez International Airport', 'Barahona', 'DO');
insert into aeroporti (nome, citta, paese) values ('RAF Alconbury', 'Huntingdon', 'GB');
insert into aeroporti (nome, citta, paese) values ('Rafael Hernandez Airport', 'Aguadilla', 'PR');
insert into aeroporti (nome, citta, paese) values ('Pittsfield Municipal Airport', 'Pittsfield', 'US');
insert into aeroporti (nome, citta, paese) values ('Pangborn Memorial Airport', 'Wenatchee', 'US');
insert into aeroporti (nome, citta, paese) values ('Saskylakh Airport', 'Saskylakh', 'RU');
insert into aeroporti (nome, citta, paese) values ('Kalakaket Creek AS Airport', 'Kalakaket Creek', 'US');
insert into aeroporti (nome, citta, paese) values ('Camden Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Boundary Airport', 'Boundary', 'US');
insert into aeroporti (nome, citta, paese) values ('Sudbury Airport', 'Sudbury', 'CA');
insert into aeroporti (nome, citta, paese) values ('Chicago Rockford International Airport', 'Chicago/Rockford', 'US');
insert into aeroporti (nome, citta, paese) values ('Sugimanuru Airport', 'Raha-Muna Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Ghriss Airport', null, 'DZ');
insert into aeroporti (nome, citta, paese) values ('Baures Airport', 'Baures', 'BO');
insert into aeroporti (nome, citta, paese) values ('Corozal Municipal Airport', 'Corozal', 'BZ');
insert into aeroporti (nome, citta, paese) values ('Chania International Airport', 'Souda', 'GR');
insert into aeroporti (nome, citta, paese) values ('Mulege Airport', 'Mulege', 'MX');
insert into aeroporti (nome, citta, paese) values ('Gelephu Airport', 'Gelephu', 'BT');
insert into aeroporti (nome, citta, paese) values ('Brescia Airport', 'Montichiari (BS)', 'IT');
insert into aeroporti (nome, citta, paese) values ('Songwe Airport', 'Mbeya', 'TZ');
insert into aeroporti (nome, citta, paese) values ('Néma Airport', 'Néma', 'MR');
insert into aeroporti (nome, citta, paese) values ('Nanchang Changbei International Airport', 'Nanchang', 'CN');
insert into aeroporti (nome, citta, paese) values ('Tifalmin Airport', 'Tifalmin', 'PG');
insert into aeroporti (nome, citta, paese) values ('Major Brigadeiro Trompowsky Airport', 'Varginha', 'BR');
insert into aeroporti (nome, citta, paese) values ('Nusawiru Airport', 'Cijulang', 'ID');
insert into aeroporti (nome, citta, paese) values ('El Debba Airport', 'El Debba', 'SD');
insert into aeroporti (nome, citta, paese) values ('Jacksonville Executive at Craig Airport', 'Jacksonville', 'US');
insert into aeroporti (nome, citta, paese) values ('Ogubsucum Airport', 'Ustupo', 'PA');
insert into aeroporti (nome, citta, paese) values ('Vienna International Airport', 'Vienna', 'AT');
insert into aeroporti (nome, citta, paese) values ('Pureni Airport', 'Pureni', 'PG');
insert into aeroporti (nome, citta, paese) values ('Manapouri Airport', null, 'NZ');
insert into aeroporti (nome, citta, paese) values ('Bartlett Cove Seaplane Base', 'Gustavus', 'US');
insert into aeroporti (nome, citta, paese) values ('Saint-Yan Airport', 'Saint-Yan', 'FR');
insert into aeroporti (nome, citta, paese) values ('Ain el Beida Airport', 'Ouargla', 'DZ');
insert into aeroporti (nome, citta, paese) values ('Rawlins Municipal Airport/Harvey Field', 'Rawlins', 'US');
insert into aeroporti (nome, citta, paese) values ('Perugia San Francesco d''Assisi – Umbria International Airport', 'Perugia', 'IT');
insert into aeroporti (nome, citta, paese) values ('Carriel Sur Airport', 'Concepcion', 'CL');
insert into aeroporti (nome, citta, paese) values ('Karonga Airport', 'Karonga', 'MW');
insert into aeroporti (nome, citta, paese) values ('Bari Karol Wojtyła Airport', 'Bari', 'IT');
insert into aeroporti (nome, citta, paese) values ('Malamala Airport', 'Malamala', 'ZA');
insert into aeroporti (nome, citta, paese) values ('Chiang Mai International Airport', 'Chiang Mai', 'TH');
insert into aeroporti (nome, citta, paese) values ('Gjögur Airport', 'Gjögur', 'IS');
insert into aeroporti (nome, citta, paese) values ('Fianarantsoa Airport', null, 'MG');
insert into aeroporti (nome, citta, paese) values ('Boryspil International Airport', 'Kiev', 'UA');
insert into aeroporti (nome, citta, paese) values ('Thisted Airport', 'Thisted', 'DK');
insert into aeroporti (nome, citta, paese) values ('Francisco Sarabia International Airport', 'Torreón', 'MX');
insert into aeroporti (nome, citta, paese) values ('Mildura Airport', 'Mildura', 'AU');
insert into aeroporti (nome, citta, paese) values ('Fillmore Municipal Airport', 'Fillmore', 'US');
insert into aeroporti (nome, citta, paese) values ('Melinda Airport', 'Melinda', 'BZ');
insert into aeroporti (nome, citta, paese) values ('Little Rock Air Force Base', 'Jacksonville', 'US');
insert into aeroporti (nome, citta, paese) values ('Dehradun Airport', 'Dehradun', 'IN');
insert into aeroporti (nome, citta, paese) values ('Talagi Airport', 'Archangelsk', 'RU');
insert into aeroporti (nome, citta, paese) values ('Barakoma Airport', 'Barakoma', 'SB');
insert into aeroporti (nome, citta, paese) values ('Mélio Viana Airport', 'Três Corações', 'BR');
insert into aeroporti (nome, citta, paese) values ('Bird Island Airport', 'Bird Island', 'SC');
insert into aeroporti (nome, citta, paese) values ('Halifax / Stanfield International Airport', 'Halifax', 'CA');
insert into aeroporti (nome, citta, paese) values ('Chehalis Centralia Airport', 'Chehalis', 'US');
insert into aeroporti (nome, citta, paese) values ('Willmar Municipal -John L Rice Field', 'Willmar', 'US');
insert into aeroporti (nome, citta, paese) values ('Warangal Airport', 'Warangal', 'IN');
insert into aeroporti (nome, citta, paese) values ('Rokot Airport', 'Sipora Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Pisa International Airport', 'Pisa', 'IT');
insert into aeroporti (nome, citta, paese) values ('Halli Airport', 'Halli / Kuorevesi', 'FI');
insert into aeroporti (nome, citta, paese) values ('Reykhólar Airport', 'Reykhólar', 'IS');
insert into aeroporti (nome, citta, paese) values ('Puerto Cabezas Airport', 'Puerto Cabezas', 'NI');
insert into aeroporti (nome, citta, paese) values ('Sabha Airport', 'Sabha', 'LY');
insert into aeroporti (nome, citta, paese) values ('Maku National Airport', 'Showt', 'IR');
insert into aeroporti (nome, citta, paese) values ('Loreto International Airport', 'Loreto', 'MX');
insert into aeroporti (nome, citta, paese) values ('Flugplatz Güttin / Rügen', 'Rügen', 'DE');
insert into aeroporti (nome, citta, paese) values ('Rehoboth Airport', 'Rehoboth Beach', 'US');
insert into aeroporti (nome, citta, paese) values ('Hangzhou Xiaoshan International Airport', 'Hangzhou', 'CN');
insert into aeroporti (nome, citta, paese) values ('Ashland Municipal Sumner Parker Field', 'Ashland', 'US');
insert into aeroporti (nome, citta, paese) values ('Jabalpur Airport', null, 'IN');
insert into aeroporti (nome, citta, paese) values ('Shanghai Pudong International Airport', 'Shanghai', 'CN');
insert into aeroporti (nome, citta, paese) values ('Hayward Executive Airport', 'Hayward', 'US');
insert into aeroporti (nome, citta, paese) values ('Hiva Oa-Atuona Airport', 'Hiva Oa Island', 'PF');
insert into aeroporti (nome, citta, paese) values ('Southwest Wyoming Regional Airport', 'Rock Springs', 'US');
insert into aeroporti (nome, citta, paese) values ('Nyeri Airport', 'Nyeri', 'KE');
insert into aeroporti (nome, citta, paese) values ('Petropavlosk South Airport', 'Petropavlosk', 'KZ');
insert into aeroporti (nome, citta, paese) values ('Battle Mountain Airport', 'Battle Mountain', 'US');
insert into aeroporti (nome, citta, paese) values ('Arutua Airport', null, 'PF');
insert into aeroporti (nome, citta, paese) values ('Stykkishólmur Airport', 'Stykkishólmur', 'IS');
insert into aeroporti (nome, citta, paese) values ('Erzurum International Airport', 'Erzurum', 'TR');
insert into aeroporti (nome, citta, paese) values ('Fukushima Airport', 'Sukagawa', 'JP');
insert into aeroporti (nome, citta, paese) values ('Cochrane Airport', 'Cochrane', 'CA');
insert into aeroporti (nome, citta, paese) values ('Wawoi Falls Airport', 'Wavoi Falls', 'PG');
insert into aeroporti (nome, citta, paese) values ('Mabaruma Airport', 'Mabaruma', 'GY');
insert into aeroporti (nome, citta, paese) values ('Eagle River Union Airport', 'Eagle River', 'US');
insert into aeroporti (nome, citta, paese) values ('Puerto Paez Airport', 'Puerto Paez', 'VE');
insert into aeroporti (nome, citta, paese) values ('Pondicherry Airport', 'Pondicherry', 'IN');
insert into aeroporti (nome, citta, paese) values ('General Pedro Jose Mendez International Airport', 'Ciudad Victoria', 'MX');
insert into aeroporti (nome, citta, paese) values ('Brookhaven Airport', 'Shirley', 'US');
insert into aeroporti (nome, citta, paese) values ('Capitán Av. German Quiroga G. Airport', 'San Borja', 'BO');
insert into aeroporti (nome, citta, paese) values ('Tres De Mayo Airport', 'Puerto Asís', 'CO');
insert into aeroporti (nome, citta, paese) values ('Quetzalcóatl International Airport', 'Nuevo Laredo', 'MX');
insert into aeroporti (nome, citta, paese) values ('Varandey Airport', 'Varandey', 'RU');
insert into aeroporti (nome, citta, paese) values ('Kandep Airport', 'Kandep', 'PG');
insert into aeroporti (nome, citta, paese) values ('Walcha Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Morney Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Tara Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Graz Airport', 'Graz', 'AT');
insert into aeroporti (nome, citta, paese) values ('Woodward Field', 'Camden', 'US');
insert into aeroporti (nome, citta, paese) values ('Manzhouli Xijiao Airport', null, 'CN');
insert into aeroporti (nome, citta, paese) values ('Waukon Municipal Airport', 'Waukon', 'US');
insert into aeroporti (nome, citta, paese) values ('Davison Army Air Field', 'Fort Belvoir', 'US');
insert into aeroporti (nome, citta, paese) values ('Sahabat [Sahabat 16] Airport', 'Sahabat', 'MY');
insert into aeroporti (nome, citta, paese) values ('Monterey Peninsula Airport', 'Monterey', 'US');
insert into aeroporti (nome, citta, paese) values ('Haines Junction Airport', 'Haines Junction', 'CA');
insert into aeroporti (nome, citta, paese) values ('Currillo Airport', 'Currillo', 'CO');
insert into aeroporti (nome, citta, paese) values ('Taiping Airport', 'Harbin', 'CN');
insert into aeroporti (nome, citta, paese) values ('Ugashik Airport', 'Ugashik', 'US');
insert into aeroporti (nome, citta, paese) values ('Rughenda Airfield', 'Butembo', 'CD');
insert into aeroporti (nome, citta, paese) values ('Itaperuna Airport', 'Itaperuna', 'BR');
insert into aeroporti (nome, citta, paese) values ('Sierra Grande Airport', 'Sierra Grande', 'AR');
insert into aeroporti (nome, citta, paese) values ('Casino Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Mount Washington Regional Airport', 'Whitefield', 'US');
insert into aeroporti (nome, citta, paese) values ('Biggs Army Air Field (Fort Bliss)', 'Fort Bliss/El Paso', 'US');
insert into aeroporti (nome, citta, paese) values ('Zanaga Airport', 'Zanaga', 'CG');
insert into aeroporti (nome, citta, paese) values ('Minot International Airport', 'Minot', 'US');
insert into aeroporti (nome, citta, paese) values ('Sara Airport', 'Pentecost Island', 'VU');
insert into aeroporti (nome, citta, paese) values ('El Embrujo Airport', 'Providencia', 'CO');
insert into aeroporti (nome, citta, paese) values ('Volta Grande Airport', 'Conceição Das Alagoas', 'BR');
insert into aeroporti (nome, citta, paese) values ('Iginniarfik', 'Iginniarfik', 'GL');
insert into aeroporti (nome, citta, paese) values ('Jieyang Chaoshan International Airport', 'Shantou', 'CN');
insert into aeroporti (nome, citta, paese) values ('Blue Canyon Nyack Airport', 'Emigrant Gap', 'US');
insert into aeroporti (nome, citta, paese) values ('Gibraltar Airport', 'Gibraltar', 'GI');
insert into aeroporti (nome, citta, paese) values ('Willmar Municipal -John L Rice Field', 'Willmar', 'US');
insert into aeroporti (nome, citta, paese) values ('Boun Neau Airport', 'Phongsaly', 'LA');
insert into aeroporti (nome, citta, paese) values ('Caribou Municipal Airport', 'Caribou', 'US');
insert into aeroporti (nome, citta, paese) values ('Wuhai Airport', 'Wuhai', 'CN');
insert into aeroporti (nome, citta, paese) values ('Clear Lake Metroport', 'Clear Lake', 'US');
insert into aeroporti (nome, citta, paese) values ('St. Anthony Airport', 'St. Anthony', 'CA');
insert into aeroporti (nome, citta, paese) values ('Escuela Mariscal Sucre Airport', 'Maracay', 'VE');
insert into aeroporti (nome, citta, paese) values ('Aerodromo de Chaves', 'Chaves', 'PT');
insert into aeroporti (nome, citta, paese) values ('Dr.Juan C. Angara Airport', 'Baler', 'PH');
insert into aeroporti (nome, citta, paese) values ('Il Caravaggio International Airport', 'Bergamo', 'IT');
insert into aeroporti (nome, citta, paese) values ('Manaung Airport', 'Manaung', 'MM');
insert into aeroporti (nome, citta, paese) values ('Diori Hamani International Airport', 'Niamey', 'NE');
insert into aeroporti (nome, citta, paese) values ('Selawik Airport', 'Selawik', 'US');
insert into aeroporti (nome, citta, paese) values ('London Luton Airport', 'London', 'GB');
insert into aeroporti (nome, citta, paese) values ('Phaplu Airport', 'Phaplu', 'NP');
insert into aeroporti (nome, citta, paese) values ('Sultan Abdul Halim Airport', 'Alor Satar', 'MY');
insert into aeroporti (nome, citta, paese) values ('Coldfoot Airport', 'Coldfoot', 'US');
insert into aeroporti (nome, citta, paese) values ('Borroloola Airport', null, 'AU');
insert into aeroporti (nome, citta, paese) values ('Nikolayevsk-na-Amure Airport', 'Nikolayevsk-na-Amure Airport', 'RU');
insert into aeroporti (nome, citta, paese) values ('Molokai Airport', 'Kaunakakai', 'US');
insert into aeroporti (nome, citta, paese) values ('Juana Azurduy De Padilla Airport', 'Sucre', 'BO');
insert into aeroporti (nome, citta, paese) values ('Kankesanturai Airport', 'Jaffna', 'LK');
insert into aeroporti (nome, citta, paese) values ('Terrace Bay Airport', 'Terrace Bay, ON', 'CA');
insert into aeroporti (nome, citta, paese) values ('Minchumina Airport', 'Minchumina', 'US');
insert into aeroporti (nome, citta, paese) values ('Dr.Juan C. Angara Airport', 'Baler', 'PH');
insert into aeroporti (nome, citta, paese) values ('Cedar City Regional Airport', 'Cedar City', 'US');
insert into aeroporti (nome, citta, paese) values ('Kent International Airport', 'Manston', 'GB');
insert into aeroporti (nome, citta, paese) values ('Arrachart Airport', null, 'MG');
insert into aeroporti (nome, citta, paese) values ('Lesobeng Airport', 'Lesobeng', 'LS');
insert into aeroporti (nome, citta, paese) values ('Jasper County Airport-Bell Field', 'Jasper', 'US');
insert into aeroporti (nome, citta, paese) values ('Bamiyan Airport', 'Bamiyan', 'AF');
insert into aeroporti (nome, citta, paese) values ('Ninglang Luguhu Airport', 'Ninglang', 'CN');
insert into aeroporti (nome, citta, paese) values ('Tunggul Wulung Airport', 'Cilacap-Java Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Sovetskiy Airport', 'Sovetskiy', 'RU');
insert into aeroporti (nome, citta, paese) values ('Wrangell Airport', 'Wrangell', 'US');
insert into aeroporti (nome, citta, paese) values ('Rogers Municipal Airport-Carter Field', 'Rogers', 'US');
insert into aeroporti (nome, citta, paese) values ('Murray Island Airport', 'Murray Island', 'AU');
insert into aeroporti (nome, citta, paese) values ('Araçatuba Airport', 'Araçatuba', 'BR');
insert into aeroporti (nome, citta, paese) values ('Mougulu Airport', 'Mougulu', 'PG');
insert into aeroporti (nome, citta, paese) values ('Jönköping Airport', 'Jönköping', 'SE');
insert into aeroporti (nome, citta, paese) values ('Cutral-Co Airport', 'Cutral-Co', 'AR');
insert into aeroporti (nome, citta, paese) values ('Jurado Airport', 'Jurado', 'CO');
insert into aeroporti (nome, citta, paese) values ('Shaxian Airport', 'Sanming', 'CN');
insert into aeroporti (nome, citta, paese) values ('Tri-Cities Regional TN/VA Airport', 'Bristol/Johnson/Kingsport', 'US');
insert into aeroporti (nome, citta, paese) values ('Rewa Airport, Chorhata, REWA', 'Rewa', 'IN');
insert into aeroporti (nome, citta, paese) values ('Bielefeld Airport', 'Bielefeld', 'DE');
insert into aeroporti (nome, citta, paese) values ('Kokomo Municipal Airport', 'Kokomo', 'US');
insert into aeroporti (nome, citta, paese) values ('Helsinki Malmi Airport', 'Helsinki', 'FI');
insert into aeroporti (nome, citta, paese) values ('Rokot Airport', 'Rokot-Sumatra Island', 'ID');
insert into aeroporti (nome, citta, paese) values ('Gamboma Airport', 'Gamboma', 'CG');
insert into aeroporti (nome, citta, paese) values ('Sabha Airport', 'Sabha', 'LY');
insert into aeroporti (nome, citta, paese) values ('Opuwa Airport', 'Opuwa', 'NA');
insert into aeroporti (nome, citta, paese) values ('Suabi Airport', null, 'PG');
insert into aeroporti (nome, citta, paese) values ('Hillenbrand Industries Airport', 'Batesville', 'US');
insert into aeroporti (nome, citta, paese) values ('Alligandi Airport', 'Alligandi', 'PA');
insert into aeroporti (nome, citta, paese) values ('Pasighat Airport', 'Pasighat', 'IN');
insert into aeroporti (nome, citta, paese) values ('Soko Airport', 'Bondoukou', 'CI');
insert into aeroporti (nome, citta, paese) values ('Perai Tepuy Airport', null, 'VE');
insert into aeroporti (nome, citta, paese) values ('Tabubil Airport', 'Tabubil', 'PG');
insert into aeroporti (nome, citta, paese) values ('Three Rivers Municipal Dr Haines Airport', 'Three Rivers', 'US');
